import { Question } from '../../types';

export const CAT1D_QUESTIONS: Question[] = [
// I-D-a: エネルギー供給（9問）
  { id: 'q-1d-a-01', category_id: 'cat-1d', body: 'エネルギー源をクレアチン酸とするものは次のうちどれ', choices: [{ label: 'a', text: '速い解糖' }, { label: 'b', text: 'ホスファゲン' }, { label: 'c', text: '酸化機構' }], correct_choice: 'b', explanation: 'エネルギー源をクレアチン酸とするものはホスファゲン', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-1d-a-02', category_id: 'cat-1d', body: 'エクササイズを開始した際、一番はじめに供給させるものは次のうちどれ', choices: [{ label: 'a', text: 'ホスファゲン' }, { label: 'b', text: '遅い解糖' }, { label: 'c', text: '速い解糖' }], correct_choice: 'a', explanation: 'エクササイズを開始した際はホスファゲンから供給される', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-1d-a-03', category_id: 'cat-1d', body: 'エネルギー源をビルピン酸とするものは次のうちどれ', choices: [{ label: 'a', text: 'ホスファゲン' }, { label: 'b', text: '遅い解糖' }, { label: 'c', text: '酸化機構' }], correct_choice: 'c', explanation: 'エネルギー源をビルピン酸とするものは酸化機構', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-1d-a-04', category_id: 'cat-1d', body: '脂肪燃焼の割合が一番高いものは次のうちどれ', choices: [{ label: 'a', text: 'V02max / 35%' }, { label: 'b', text: 'V02max / 45%' }, { label: 'c', text: 'V02max / 25%' }], correct_choice: 'c', explanation: 'V02maxとは最大酸素摂取量。％は強度を表す。強度が高いほど脂肪だけでなく糖質燃焼するので強度が一番低いものになる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-1d-a-05', category_id: 'cat-1d', body: '100m走によるATPの供給が最も大きいのは次のうちどれ', choices: [{ label: 'a', text: 'ホスファゲン' }, { label: 'b', text: '酸化機構' }, { label: 'c', text: '速い解糖' }], correct_choice: 'a', explanation: '100m走は高パワーが必要となるため、ATPの供給が最も大きいのはホスファゲン', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-1d-a-06', category_id: 'cat-1d', body: '乳酸が生産されるのは次のうちどれ', choices: [{ label: 'a', text: '酸化機構' }, { label: 'b', text: '速い解糖' }, { label: 'c', text: '遅い解糖' }], correct_choice: 'b', explanation: '乳酸が生産されるのは速い解糖', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-1d-a-07', category_id: 'cat-1d', body: '供給時間が遅い順番になっているのは次のうちどれ ①ホスファゲン ②遅い解糖 ③速い解糖 ④酸化機構', choices: [{ label: 'a', text: '④ → ③ → ② → ①' }, { label: 'b', text: '④ → ② → ③ → ①' }, { label: 'c', text: '① → ③ → ② → ④' }], correct_choice: 'b', explanation: '酸化機構→遅い解糖→速い解糖→ホスファゲン', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-1d-a-08', category_id: 'cat-1d', body: '筋がコンセントリック時のエネルギー源は次のうちどれ', choices: [{ label: 'a', text: 'ATP' }, { label: 'b', text: 'トリグリセリド' }, { label: 'c', text: 'ミトコンドリア' }], correct_choice: 'a', explanation: '筋のエネルギー源はATP（アデノシン3リン酸）', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-1d-a-09', category_id: 'cat-1d', body: '供給速度が一番遅いものは次のうちどれ', choices: [{ label: 'a', text: '遅い解糖' }, { label: 'b', text: '酸化機構' }, { label: 'c', text: 'ホスファゲン' }], correct_choice: 'b', explanation: '供給速度が一番遅いものは酸化機構', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
// I-D-b: 三大栄養素（17問）
  { id: 'q-1d-b-01', category_id: 'cat-1d', body: '炭水化物300g タンパク質250g 脂質100g、適切なアドバイスはどれか', choices: [{ label: 'a', text: 'タンパク質を増やしてください' }, { label: 'b', text: '脂質を減らしてください' }, { label: 'c', text: '炭水化物を増やして、タンパク質を減らしてください' }], correct_choice: 'c', explanation: '炭水化物の割合が少なく、タンパク質の割合が高いため 炭水化物300×4=1,200kcal タンパク質250×4=1,000kcal 脂質100×9=900kcal 総Kcal3,100kcal', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-1d-b-02', category_id: 'cat-1d', body: '炭水化物50g タンパク質30g 脂質35gの時、総kcalは次のうちどれ', choices: [{ label: 'a', text: '635 kcal' }, { label: 'b', text: '615 kcal' }, { label: 'c', text: '625 kcal' }], correct_choice: 'a', explanation: '炭水化物50×4=200kcal タンパク質30×4=120kcal 脂質35×9=315kcal 総Kcal200+120+315=635kcal', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-1d-b-03', category_id: 'cat-1d', body: '身長170cmの体重65kgの非運動的な成人が1日当たり必要なタンパク質は次のうちどれ', choices: [{ label: 'a', text: '52g' }, { label: 'b', text: '65g' }, { label: 'c', text: '54g' }], correct_choice: 'a', explanation: '非運動的な成人が１日当たり必要なタンパク質は0.8g/kgになるため 65×0.8=52', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-1d-b-04', category_id: 'cat-1d', body: 'あるクライアントは1日2,500kcal摂取している。無酸素トレーニング500kcal、有酸素トレーニング700kcal消費した 基礎代謝が1,500kcalある時の体重は次のうちどのようになる', choices: [{ label: 'a', text: '増加する' }, { label: 'b', text: '変わらない' }, { label: 'c', text: '減少する' }], correct_choice: 'c', explanation: '摂取しているkcalよりも消費しているkcalのほうが多いため体重は減少する。摂取2,500kcal 消費500+700+1,500=2,700kcal', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-1d-b-05', category_id: 'cat-1d', body: '三大栄養素として誤っているものは次のうちどれ', choices: [{ label: 'a', text: '脂質' }, { label: 'b', text: 'タンパク質' }, { label: 'c', text: 'ビタミン' }], correct_choice: 'c', explanation: 'ビタミンは三大栄養素ではなく、五大栄養素に含む', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-1d-b-06', category_id: 'cat-1d', body: 'タンパク質が身体で分解されると次のうちどれになる', choices: [{ label: 'a', text: 'アミノ酸' }, { label: 'b', text: '必須脂肪酸' }, { label: 'c', text: 'グルコース' }], correct_choice: 'a', explanation: 'タンパク質は身体の中で分解されアミノ酸となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-1d-b-07', category_id: 'cat-1d', body: '炭水化物481g タンパク質175g 脂質98g、適切なアドバイスはどれか', choices: [{ label: 'a', text: '現状のままで問題ございません' }, { label: 'b', text: '炭水化物を増やしてください' }, { label: 'c', text: '脂質を減らしてください' }], correct_choice: 'a', explanation: '摂取比率はギリギリ合っている 炭水化物481×4=1,924kcal タンパク質175×4=700kcal 脂質98×9=882kcal 総Kcal3,506kcal', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },
  { id: 'q-1d-b-08', category_id: 'cat-1d', body: '炭水化物400g タンパク質140g 脂質70gの時、総kcalは次のうちどれ', choices: [{ label: 'a', text: '2,775 kcal' }, { label: 'b', text: '2,790 kcal' }, { label: 'c', text: '2,800 kcal' }], correct_choice: 'b', explanation: '炭水化物400×4=1,600kcal タンパク質140×4=560kcal 脂質70×9=630kcal 総Kcal1,600+560+630=2,790kcal', source: 'NEXT TRAINER LAB', is_free: true, display_order: 17 },
  { id: 'q-1d-b-09', category_id: 'cat-1d', body: '炭水化物300g タンパク質200g 脂質45gの時、タンパク質が総kcalのうち占めている％は次のうちどれ', choices: [{ label: 'a', text: '33%' }, { label: 'b', text: '31%' }, { label: 'c', text: '29%' }], correct_choice: 'a', explanation: '炭水化物300×4=1,200kcal タンパク質200×4=800kcal 脂質45×9=405kcal 総Kcal2,405kcal タンパク質800÷2,405=約33%', source: 'NEXT TRAINER LAB', is_free: true, display_order: 18 },
  { id: 'q-1d-b-10', category_id: 'cat-1d', body: '炭水化物500g タンパク質275g 脂質100gの時 炭水化物が総kcalのうち占めている％は次のうちどれ', choices: [{ label: 'a', text: '55%' }, { label: 'b', text: '50%' }, { label: 'c', text: '45%' }], correct_choice: 'b', explanation: '炭水化物500×4=2,000kcal タンパク質275×4=1,100kcal 脂質100×9=900kcal 総Kcal4,000kcal 炭水化物2,000÷4,000=50%', source: 'NEXT TRAINER LAB', is_free: true, display_order: 19 },
  { id: 'q-1d-b-11', category_id: 'cat-1d', body: '身長155cmの体重55kgのアスリートが1日当たり必要な炭水化物はどれ', choices: [{ label: 'a', text: '370~510g' }, { label: 'b', text: '380~500g' }, { label: 'c', text: '385~550g' }], correct_choice: 'c', explanation: 'アスリートが１日当たり必要な炭水化物は7~10g/kgになるため 55×7=385 55×10=550', source: 'NEXT TRAINER LAB', is_free: true, display_order: 20 },
  { id: 'q-1d-b-12', category_id: 'cat-1d', body: '完全タンパク質の食材は次のうちどれ', choices: [{ label: 'a', text: '豆類' }, { label: 'b', text: '卵' }, { label: 'c', text: 'ピーナッツ' }], correct_choice: 'b', explanation: '完全タンパク質の食材は卵になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 21 },
  { id: 'q-1d-b-13', category_id: 'cat-1d', body: 'あるクライントは1日2,800kcal摂取している。無酸素トレーニング400kcal、有酸素トレーニング900kcal消費した。基礎代謝が1,500kcalある時クライントの体重は次のうちどのようになる', choices: [{ label: 'a', text: '増加する' }, { label: 'b', text: '変わらない' }, { label: 'c', text: '減少する' }], correct_choice: 'b', explanation: '摂取しているkcalと消費しているkcalが同じのため体重は変わらない。摂取2,800kcal 消費400+900+1,500=2,800kcal', source: 'NEXT TRAINER LAB', is_free: true, display_order: 22 },
  { id: 'q-1d-b-14', category_id: 'cat-1d', body: '1gのkcalとして同じkcalではない栄養素は次のうちどれ', choices: [{ label: 'a', text: 'タンパク質' }, { label: 'b', text: '脂質' }, { label: 'c', text: '炭水化物' }], correct_choice: 'b', explanation: '脂質のみ9kcal/gになり、炭水化物・タンパク質は4kcal/g', source: 'NEXT TRAINER LAB', is_free: true, display_order: 23 },
  { id: 'q-1d-b-15', category_id: 'cat-1d', body: 'あるクライントは1日3,000kcal摂取していたが、タンパク質を100g増やした。無酸素トレーニング600kcal、有酸素トレーニングで1,000kcal消費した。基礎代謝が1,600kcalある時の体重はどのようになる', choices: [{ label: 'a', text: '変わらない' }, { label: 'b', text: '減少する' }, { label: 'c', text: '増加する' }], correct_choice: 'c', explanation: '摂取しているkcalよりも消費しているkcalのほうが少ないため体重は増加する。摂取3,000+400=3,400kcal 消費600+1,000+1,600=3,200kcal', source: 'NEXT TRAINER LAB', is_free: true, display_order: 24 },
  { id: 'q-1d-b-16', category_id: 'cat-1d', body: 'トレーニング後に素早くグリコーゲンを回復させるためには次のどの栄養素を摂取するべきか', choices: [{ label: 'a', text: '脂質' }, { label: 'b', text: '炭水化物' }, { label: 'c', text: 'タンパク質' }], correct_choice: 'b', explanation: '炭水化物（糖質）はグルコースを吸収してグリコーゲンが作られるため', source: 'NEXT TRAINER LAB', is_free: true, display_order: 25 },
  { id: 'q-1d-b-17', category_id: 'cat-1d', body: '炭水化物375g タンパク質150g 脂質100gの時 脂質が総kcalのうち占めている％は次のうちどれ', choices: [{ label: 'a', text: '35%' }, { label: 'b', text: '30%' }, { label: 'c', text: '25%' }], correct_choice: 'b', explanation: '炭水化物375×4=1,500kcal タンパク質150×4=600kcal 脂質100×9=900kcal 総Kcal3,000kcal 脂質900÷3,000=30%', source: 'NEXT TRAINER LAB', is_free: true, display_order: 26 },
// I-D-c: 水分補給（3問）
  { id: 'q-1d-c-01', category_id: 'cat-1d', body: '身長170cm体重68kgのクライアントがトレーニング2時間前の水分補給として正しいのは次のうちどれ', choices: [{ label: 'a', text: '650~756ml' }, { label: 'b', text: '340~476ml' }, { label: 'c', text: '204~340ml' }], correct_choice: 'c', explanation: '2時間前の水分補給としては3~5ml/kgなので 68×3=204 68×5=340', source: 'NEXT TRAINER LAB', is_free: true, display_order: 27 },
  { id: 'q-1d-c-02', category_id: 'cat-1d', body: '身長158cm体重50kgのクライアントがトレーニング4時間前の水分補給として正しいのは次のうちどれ', choices: [{ label: 'a', text: '250~350ml' }, { label: 'b', text: '600~700ml' }, { label: 'c', text: '350~500ml' }], correct_choice: 'a', explanation: '4時間前の水分補給としては5~7ml/kgなので 50×5=250 50×7=350', source: 'NEXT TRAINER LAB', is_free: true, display_order: 28 },
  { id: 'q-1d-c-03', category_id: 'cat-1d', body: 'トレーニング終了時に、体重が0.9kg減少していた場合、水分補給の目安は次のうちどれ', choices: [{ label: 'a', text: '1.8L' }, { label: 'b', text: '1.3L' }, { label: 'c', text: '1.0L' }], correct_choice: 'b', explanation: '練習後の水分補給としては、体重450g減るに当たり600~700mlなので 900÷450=2 600×2=1,200 700×2=1,400 1.2L~1.4L', source: 'NEXT TRAINER LAB', is_free: true, display_order: 29 },
];
