import { Question } from '../../types';

export const CAT1A_QUESTIONS: Question[] = [
// I-A-a: 初回面談と健康評価（7問）
  { id: 'q-1a-a-01', category_id: 'cat-1a', body: '初回面談の順番として正しい順番は次のうちどれか ①目標の確認 ②クライアントとトレーナーの適合性の確認 ③契約', choices: [{ label: 'a', text: '② → ① → ③' }, { label: 'b', text: '③ → ① → ②' }, { label: 'c', text: '① → ③ → ②' }], correct_choice: 'a', explanation: '契約までは ①クライアントとトレーナーの適合性の確認→②目標の確認→③契約', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-1a-a-02', category_id: 'cat-1a', body: 'トレーナーがクライアントと契約を交わす前に、必要がないものはどれか', choices: [{ label: 'a', text: '目標についての話し合い' }, { label: 'b', text: 'サービスの説明' }, { label: 'c', text: 'クライアントの意識調査' }], correct_choice: 'c', explanation: 'クライアントの意識調査は契約後に行うもので、契約前には必要ない。契約前に必要なのは①適合性の確認 ②目標の話し合い ③サービスの説明', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-1a-a-03', category_id: 'cat-1a', body: '健康評価スクリーニングの目的は次のうちどれか', choices: [{ label: 'a', text: 'クライアントの健康を評価して改善する' }, { label: 'b', text: '医師への照会が必要かどうかを判断するため' }, { label: 'c', text: '意識レベルを確認するため' }], correct_choice: 'b', explanation: '健康評価スクリーニングは医師への照会が必要かどうかを判断する目的がある', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-1a-a-04', category_id: 'cat-1a', body: 'クライアントにインフォームドコンセントを記入してもらうのはどれか', choices: [{ label: 'a', text: '体力評価の結果と同時に' }, { label: 'b', text: '体力評価の前' }, { label: 'c', text: '体力評価が終わった後日' }], correct_choice: 'b', explanation: 'インフォームドコンセントはプログラムの実施システムの内容や手順に関する情報が記載されているため体力評価前に記入してもらう', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-1a-a-05', category_id: 'cat-1a', body: '今まで10年間高齢者の方に指導していたが、20代のクライアントからコンテスト大会に向けて指導の申し込みがあった際、適切な対応はどれ。', choices: [{ label: 'a', text: 'コンテスト大会に精通しているトレーナーを紹介する' }, { label: 'b', text: '今までと変わらずトレーニングメニューを作成する' }, { label: 'c', text: '受けられないと断る' }], correct_choice: 'a', explanation: '今まで指導してきたクラアントの年齢・性別・目的等がかけ離れていた場合、指導実績が多いトレーナーを紹介する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-1a-a-06', category_id: 'cat-1a', body: 'クライアントに病歴をヒヤリングするのは、次のうちどの時点か', choices: [{ label: 'a', text: '健康評価スクリーニング時' }, { label: 'b', text: '初回セッション後' }, { label: 'c', text: '補助的スクリーニング時' }], correct_choice: 'a', explanation: '病歴をヒヤリングするのは健康評価スクリーニング時にする', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-1a-a-07', category_id: 'cat-1a', body: '補助的スクリーニングではないものは次のうちどれ', choices: [{ label: 'a', text: '生活習慣調査' }, { label: 'b', text: 'PAR-Q' }, { label: 'c', text: '危険の引受承諾書' }], correct_choice: 'b', explanation: 'PAR-Q（身体活動質問表）は健康評価スクリーニング時に行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
// I-A-b: 冠状動脈疾患の危険因子（7問）
  { id: 'q-1a-b-01', category_id: 'cat-1a', body: '以下は55歳女性のクライアントの健康評価結果です。クライアントの危険因子の数は次のうちどれ 身長：152cm ・体重：55kg ・血圧：145/98mmHg LDLコレステロール：120mg/dl・HDLコレステロール：35mg/dl 叔父が50歳で心臓発作を発症', choices: [{ label: 'a', text: '３個' }, { label: 'b', text: '２個' }, { label: 'c', text: '4個' }], correct_choice: 'c', explanation: '①年齢：55歳女性 →女性55歳以上で陽性\n②血圧：145/98 →収縮期≧130で陽性\n③血圧：145/98 →拡張期≧80で陽性\n④HDL：35mg/dl →HDL40mg以下で陽性\n\n※LDL120は130未満なので陰性\n※叔父は直系家族ではないので対象外\n※BMI=55÷(1.52×1.52)=23.8で陰性', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-1a-b-02', category_id: 'cat-1a', body: '年齢の冠状動脈疾患の危険因子について陽性の正しい組み合わせはどれか ①男性45歳以上 ②男性55歳以上 ③女性45歳以上 ④女性55歳以上', choices: [{ label: 'a', text: '①と③' }, { label: 'b', text: '①と④' }, { label: 'c', text: '②と④' }], correct_choice: 'b', explanation: '年齢の危険因子は男性45歳以上・女性55歳以上が陽性', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-1a-b-03', category_id: 'cat-1a', body: '家族歴(突然死)の冠状動脈疾患の危険因子について陽性の正しい組み合わせは次のうちどれ ①男性家族45歳以前 ②男性家族55歳以前 ③女性家族55歳以前 ④女性家族65歳以前', choices: [{ label: 'a', text: '②と③' }, { label: 'b', text: '②と④' }, { label: 'c', text: '①と③' }], correct_choice: 'b', explanation: '家族歴の危険因子は男性家族55歳以前・女性65歳が陽性', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-1a-b-04', category_id: 'cat-1a', body: 'ウエストサイズの冠状動脈疾患 危険因子について陽性の組み合わせはどれ ①男性104cm以上 ②男性102cm以上 ③女性88cm以上 ④女性78cm以上', choices: [{ label: 'a', text: '②と③' }, { label: 'b', text: '①と④' }, { label: 'c', text: '①と③' }], correct_choice: 'a', explanation: 'ウエストサイズの危険因子は男性102cm以上・女性88cm以上が陽性', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-1a-b-05', category_id: 'cat-1a', body: 'コレステロールの冠状動脈疾患 危険因子について陽性の組み合わせはどれか ①LDL130mg以上 ②LDL130mg以下 ③HDL40mg以下 ④HDL45mg以下', choices: [{ label: 'a', text: '②と④' }, { label: 'b', text: '①と③' }, { label: 'c', text: '②と③' }], correct_choice: 'b', explanation: 'コレステロールの危険因子はLDL130mg以上・HDL40mg以下が陽性', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-1a-b-06', category_id: 'cat-1a', body: '血圧の冠状動脈疾患の危険因子について陽性の正しいのは次のどれか ①収縮期≧135mmHg ②収縮期≧130mmHg ③拡張期≧70mmHg ④拡張期≧80mmHg', choices: [{ label: 'a', text: '②と④' }, { label: 'b', text: '①と④' }, { label: 'c', text: '①と③' }], correct_choice: 'a', explanation: '血圧の危険因子は収縮期≧130mmHg・拡張期≧80mmHgが陽性', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-1a-b-07', category_id: 'cat-1a', body: '以下は40歳男性のクライアントの健康評価結果です。クライアントの危険因子の数は次のうちどれ 身長：175cm ・体重：98kg ・血圧：120/79mmHg LDLコレステロール：155mg/dl ・HDLコレステロール：70mg/dl 母親が50歳で心筋梗塞によって亡くなっている', choices: [{ label: 'a', text: '2個' }, { label: 'b', text: '4個' }, { label: 'c', text: '3個' }], correct_choice: 'a', explanation: '陽性①BMI：98÷(1.75×1.75)=32 →BMI30以上で陽性\n陽性②LDL：155mg/dl →LDL130mg以上で陽性\n陽性③家族歴：母親が50歳で心筋梗塞 →女性家族65歳以前で陽性\n陰性④HDL：70mg/dl →HDL60mg以上で陰性因子（陽性を1つ打ち消す）\n\n陽性3個 − 陰性1個 = 2個\n\n※年齢：40歳男性 →男性45歳以上が陽性なので陰性\n※血圧：120/79 →基準値以下で陰性', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
];
