import { Question } from '../../types';

export const CAT1C_QUESTIONS: Question[] = [
// I-C-a: 目標（9問）
  { id: 'q-1c-a-01', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、本人の記録に対しての目標', choices: [{ label: 'a', text: '成果目標' }, { label: 'b', text: '過程目標' }, { label: 'c', text: 'パフォーマンス目標' }], correct_choice: 'c', explanation: '本人のパフォーマンス(記録)に対しての目標のため', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-1c-a-02', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、スクワットで友達より高重量をあげられるようになる', choices: [{ label: 'a', text: '過程目標' }, { label: 'b', text: '成果目標' }, { label: 'c', text: 'パフォーマンス目標' }], correct_choice: 'b', explanation: '友達と言う比較対象があり、本人の努力では達成できない目標の為', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-1c-a-03', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、人と比較することで頑張ることができる方の努力を引き出すことができる', choices: [{ label: 'a', text: '成果目標' }, { label: 'b', text: 'パフォーマンス目標' }, { label: 'c', text: '過程目標' }], correct_choice: 'a', explanation: '比較対象があり、本人の努力では達成できない目標設定', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-1c-a-04', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、本人の努力ではコントロールできない。他人と比較する。', choices: [{ label: 'a', text: '成果目標' }, { label: 'b', text: 'パフォーマンス目標' }, { label: 'c', text: '過程目標' }], correct_choice: 'a', explanation: '競争相手が存在し、本人の努力ではコントロールできない目標', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-1c-a-05', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、体脂肪を４kg落とす', choices: [{ label: 'a', text: '成果目標' }, { label: 'b', text: '過程目標' }, { label: 'c', text: 'パフォーマンス目標' }], correct_choice: 'c', explanation: '体脂肪を4kg落とすと言う、パフォーマンス(記録)を目標としている為', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-1c-a-06', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、エクササイズの習慣を維持するために重要', choices: [{ label: 'a', text: '成果目標' }, { label: 'b', text: '過程目標' }, { label: 'c', text: 'パフォーマンス目標' }], correct_choice: 'b', explanation: 'エクササイズの習慣を維持するのは自分で一番コントロールしやすい目標設定', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-1c-a-07', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、本人の努力で必ず達成できる目標', choices: [{ label: 'a', text: '過程目標' }, { label: 'b', text: 'パフォーマンス目標' }, { label: 'c', text: '成果目標' }], correct_choice: 'a', explanation: '本人の努力で必ず達成できる目標は過程目標', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-1c-a-08', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、毎晩寝る前にストレッチをする', choices: [{ label: 'a', text: '成果目標' }, { label: 'b', text: 'パフォーマンス目標' }, { label: 'c', text: '過程目標' }], correct_choice: 'c', explanation: '毎晩寝る前にストレッチをすると言う、本人の努力で達成できる為', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-1c-a-09', category_id: 'cat-1c', body: '次の説明と目標はどの目標種類に分けられるか、本人の個人的な記録基準に関して目標設定する', choices: [{ label: 'a', text: '過程目標' }, { label: 'b', text: '成果目標' }, { label: 'c', text: 'パフォーマンス目標' }], correct_choice: 'c', explanation: '記録(パフォーマンス)基準に関して目標設定をするため', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
// I-C-b: 動機付け（12問）
  { id: 'q-1c-b-01', category_id: 'cat-1c', body: '約束を守らなかったので明日は居残りをしてください。動機付けはどれか', choices: [{ label: 'a', text: 'ネガティブな強化' }, { label: 'b', text: 'ポジティブな罰' }, { label: 'c', text: 'ポジティブな強化' }, { label: 'd', text: 'ネガティブな罰' }], correct_choice: 'b', explanation: '居残りが与えられ嫌だ →ポジティブな罰', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-1c-b-02', category_id: 'cat-1c', body: '次の説明と動機はどちらの動機に分けられるか、外的に嬉しい事を得ようとする考え', choices: [{ label: 'a', text: '外発的動機' }, { label: 'b', text: '内発的動機' }], correct_choice: 'a', explanation: '', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-1c-b-03', category_id: 'cat-1c', body: '片付けをしていなかったので、明日のケーキは食べたらダメです。動機付けは次のうちどれ', choices: [{ label: 'a', text: 'ネガティブな強化' }, { label: 'b', text: 'ネガティブな罰' }, { label: 'c', text: 'ポジティブな罰' }, { label: 'd', text: 'ポジティブな強化' }], correct_choice: 'b', explanation: 'ケーキが取り除かれ、嫌だ →ネガティブな罰', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-1c-b-04', category_id: 'cat-1c', body: 'スクワットで+20kgできたら、欲しかった時計を買ってあげるよ！動機付けは次のうちどれ', choices: [{ label: 'a', text: 'ポジティブな罰' }, { label: 'b', text: 'ネガティブな罰' }, { label: 'c', text: 'ポジティブな強化' }, { label: 'd', text: 'ネガティブな強化' }], correct_choice: 'c', explanation: '欲しかった時計が与えられ、嬉しい →ポジティブな強化', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-1c-b-05', category_id: 'cat-1c', body: '大会で入賞したら、居残り練習をしなくていいよ。動機付けは次のうちどれ', choices: [{ label: 'a', text: 'ポジティブな罰' }, { label: 'b', text: 'ポジティブな強化' }, { label: 'c', text: 'ネガティブな強化' }, { label: 'd', text: 'ネガティブな罰' }], correct_choice: 'c', explanation: '居残り練習が取り除かれ、嬉しい →ネガティブな強化', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-1c-b-06', category_id: 'cat-1c', body: 'ダイエット中に禁止していたお菓子をたべたので、新しい服は返品してください。上記の動機付けは次のうちどれ', choices: [{ label: 'a', text: 'ポジティブな罰' }, { label: 'b', text: 'ネガティブな強化' }, { label: 'c', text: 'ポジティブな強化' }, { label: 'd', text: 'ネガティブな罰' }], correct_choice: 'd', explanation: '新しい服が取り除かれ、嫌だ →ネガティブな罰', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-1c-b-07', category_id: 'cat-1c', body: '次の説明と動機はどちらの動機に分けられるか、自ら行う・取り組む事で楽しい事', choices: [{ label: 'a', text: '外発的動機' }, { label: 'b', text: '内発的動機' }], correct_choice: 'b', explanation: '', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },
  { id: 'q-1c-b-08', category_id: 'cat-1c', body: '言うこと聞かなかったら、行く予定だった遊園地には行きません。動機付けは次のうちどれ', choices: [{ label: 'a', text: 'ポジティブな強化' }, { label: 'b', text: 'ポジティブな罰' }, { label: 'c', text: 'ネガティブな罰' }, { label: 'd', text: 'ネガティブな強化' }], correct_choice: 'c', explanation: '予定していた遊園地に行くことが取り除かれ、嫌だ →ネガティブな罰', source: 'NEXT TRAINER LAB', is_free: true, display_order: 17 },
  { id: 'q-1c-b-09', category_id: 'cat-1c', body: 'ダイエットに成功したので、新しい服を買ってあげる。動機付けはどれか', choices: [{ label: 'a', text: 'ネガティブな罰' }, { label: 'b', text: 'ネガティブな強化' }, { label: 'c', text: 'ポジティブな罰' }, { label: 'd', text: 'ポジティブな強化' }], correct_choice: 'd', explanation: '新しい服を与えられて、嬉しい →ポジティブな強化', source: 'NEXT TRAINER LAB', is_free: true, display_order: 18 },
  { id: 'q-1c-b-10', category_id: 'cat-1c', body: '次の説明と動機はどちらの動機に分けられるか、もっと綺麗な身体になりたいので、トレーニングに励む', choices: [{ label: 'a', text: '内発的動機' }, { label: 'b', text: '外発的動機' }], correct_choice: 'a', explanation: '自ら綺麗な身体になりたいと取り組む楽しさを持っているので内発的動機になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 19 },
  { id: 'q-1c-b-11', category_id: 'cat-1c', body: '次の説明と動機はどちらの動機に分けられるか、好きな子に褒めてもらうために、頑張る', choices: [{ label: 'a', text: '内発的動機' }, { label: 'b', text: '外発的動機' }], correct_choice: 'b', explanation: '好きな子に褒めてもらいたいと言う外的に嬉しいことを得ようとしているので、外発的動機になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 20 },
  { id: 'q-1c-b-12', category_id: 'cat-1c', body: 'ダイエットに成功したので、重い荷物は運ばなくていいよ。動機付けはどれか', choices: [{ label: 'a', text: 'ネガティブな罰' }, { label: 'b', text: 'ネガティブな強化' }, { label: 'c', text: 'ポジティブな強化' }, { label: 'd', text: 'ポジティブな罰' }], correct_choice: 'b', explanation: '重い荷物を運ぶのを取り除かれ、嬉しい →ネガティブな強化', source: 'NEXT TRAINER LAB', is_free: true, display_order: 21 },
];
