import { Question } from '../../types';

export const CAT1B_QUESTIONS: Question[] = [
// I-B-a: 体力テスト（14問）
  { id: 'q-1b-a-01', category_id: 'cat-1b', body: '正しいテストの順番はどれ①垂直跳び ②Tテスト ③1分間プッシュアップ ④12分間走', choices: [{ label: 'a', text: '① →② →③ →④' }, { label: 'b', text: '② →③ →① →④' }, { label: 'c', text: '③ →① →④ →③' }], correct_choice: 'a', explanation: '①垂直跳び(非疲労性) →②Tテスト(アジリティ) →③1分間プッシュアップ(局所持久力) →④12分間走(有酸素能力)', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-1b-a-02', category_id: 'cat-1b', body: '正しいテストの順番はどれ①1分間プッシュアップ ②１RMレッグプレス ③近赤外線法 ④YO-YOテスト', choices: [{ label: 'a', text: '② →① →③ →④' }, { label: 'b', text: '③ →② →① →④' }, { label: 'c', text: '③ →① →④ →③' }], correct_choice: 'b', explanation: '③近赤外線法(安静時) →②1RMレッグプレス(最大筋力) →①1分間プッシュアップ(局所持久力) →④YO-YOテスト(有酸素能力)', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-1b-a-03', category_id: 'cat-1b', body: '次のテストのうち、日にちを分けた方が良いのはどれか', choices: [{ label: 'a', text: '有酸素能力テスト' }, { label: 'b', text: '無酸素性テスト' }, { label: 'c', text: 'アジリティテスト' }], correct_choice: 'a', explanation: '有酸素能力テストは別日で行ったほうが良い', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-1b-a-04', category_id: 'cat-1b', body: '正しいテストの順番はどれ①1RMベンチプレス ②300ヤードシャトルラン ③40mスプリント ④ヘキサゴンドリル', choices: [{ label: 'a', text: '① →④ →③ →②' }, { label: 'b', text: '② →③ →① →④' }, { label: 'c', text: '④ →① →③ →②' }], correct_choice: 'c', explanation: '④ヘキサゴンドリル(アジリティ) →①1RMベンチプレス(最大筋力) →③40mスプリント(スプリント) →②300ヤードシャトルラン(無酸素性)', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-1b-a-05', category_id: 'cat-1b', body: '筋力レベルが最も適切に評価できるのは、次のうちどれ', choices: [{ label: 'a', text: '自重プッシュアップ' }, { label: 'b', text: 'ベンチプレス' }, { label: 'c', text: 'ショルダープレス' }], correct_choice: 'b', explanation: '筋力レベルを測定するのはベンチプレスが適している', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-1b-a-06', category_id: 'cat-1b', body: '次のテストのうち2番目に行うものはどれ', choices: [{ label: 'a', text: 'スプリントテスト' }, { label: 'b', text: '最大パワー・最大筋力' }, { label: 'c', text: 'アジリティテスト' }], correct_choice: 'b', explanation: '正しい順番：アジリティテスト →最大パワー・最大筋力 →スプリントテスト', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-1b-a-07', category_id: 'cat-1b', body: '体重80kgのクライアントが、70kg持ち上げた時の相対的筋力指数はどれ', choices: [{ label: 'a', text: '0.875' }, { label: 'b', text: '0.925' }, { label: 'c', text: '1.0' }], correct_choice: 'a', explanation: '相対的筋力指数なので問11と同様、体重1kg当たりどれくらい持つことが できるかを求められている。相対的筋力指数は重さ÷体重で求められる70（持った重さ）÷80（体重）＝0.875', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-1b-a-08', category_id: 'cat-1b', body: 'クライアントの相対的な上肢の筋力を評価するのに適切なものはどれ', choices: [{ label: 'a', text: 'ベンチプレス 体重比の最大負荷' }, { label: 'b', text: 'ショルダープレス 1回の最大負荷測定' }, { label: 'c', text: 'プッシュアップ 最大反復回数測定' }], correct_choice: 'a', explanation: '相対的とは体重が何kgの人が1kg当たりどれくらい持つことができるのか。プッシュアップの最大反復回数は筋力を評価するのに適していない。ショルダープレスの最大負荷測定は、体重比が含まれていなく絶対評価となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-1b-a-09', category_id: 'cat-1b', body: '最初に行うテストは次のうちどれ', choices: [{ label: 'a', text: 'スプリントテスト' }, { label: 'b', text: '非疲労性テスト' }, { label: 'c', text: '安静時テスト' }], correct_choice: 'c', explanation: '最初に行うのは安静時テスト', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-1b-a-10', category_id: 'cat-1b', body: '非疲労性テストではないのは次のうちどれ', choices: [{ label: 'a', text: '身体組成' }, { label: 'b', text: 'シット＆リーチ' }, { label: 'c', text: '垂直跳び' }], correct_choice: 'a', explanation: '身体組成は安静時テスト', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-1b-a-11', category_id: 'cat-1b', body: '局所持久力テストではないのは次のうちどれ', choices: [{ label: 'a', text: 'シットアップ' }, { label: 'b', text: 'プッシュアップ' }, { label: 'c', text: 'Tテスト' }], correct_choice: 'c', explanation: 'Tテストはアジリティテスト', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-1b-a-12', category_id: 'cat-1b', body: 'フルマラソンの完走が目的に対して、行う必要がない測定は次のうちどれ', choices: [{ label: 'a', text: '12分間走' }, { label: 'b', text: 'スクワット3RMテスト' }, { label: 'c', text: 'Tテスト' }], correct_choice: 'c', explanation: 'Tテストはアジリティテストの1つで目的であるフルマラソン完走に必要がない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-1b-a-13', category_id: 'cat-1b', body: '次のテストを正しいテストの順番はどれ①アジリティテスト ②局所持久力テスト ③非疲労性テスト ④無酸素テスト', choices: [{ label: 'a', text: '③ →② →④→①' }, { label: 'b', text: '③ →① →② →④' }, { label: 'c', text: '② →③ →① →④' }], correct_choice: 'b', explanation: '③非疲労性テスト →①アジリティテスト →②局所持久力テスト →④無酸素テスト', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-1b-a-14', category_id: 'cat-1b', body: 'テストを行う順番として正しいものは次のうちどれ①40ヤード走 ②トレッドミル ③バーティカルジャンプ ④Tテスト', choices: [{ label: 'a', text: '③ → ④ → ② → ①' }, { label: 'b', text: '③ → ④ → ① → ②' }, { label: 'c', text: '② → ③ → ④ → ①' }], correct_choice: 'b', explanation: '③バーティカルジャンプ(非疲労性) →④Tテスト(アジリティ) →①40ヤード走(スプリント) →②トレッドミル(有酸素能力)', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
// I-B-b: 皮脂厚測定（7問）
  { id: 'q-1b-b-01', category_id: 'cat-1b', body: '皮脂厚測定において斜めにつまむのは次のうちどれ', choices: [{ label: 'a', text: '下腿内側部' }, { label: 'b', text: '腹部' }, { label: 'c', text: '肩甲骨下筋' }], correct_choice: 'c', explanation: '斜めにつまむのは胸部・肩甲骨下筋・腸骨上部', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-1b-b-02', category_id: 'cat-1b', body: '初心者のクライアントが初めてジムで行う、形態測定方法は次のうちどれ', choices: [{ label: 'a', text: 'BMI' }, { label: 'b', text: '皮脂厚測定' }, { label: 'c', text: '生体インピーダンス法' }], correct_choice: 'a', explanation: '初めてジムに来たクライアントに対しては、最も簡易的な測定方法で行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },
  { id: 'q-1b-b-03', category_id: 'cat-1b', body: '腹部の皮脂厚測定において正しい説明は次のうちどれ', choices: [{ label: 'a', text: '臍から約2cm離れた部位を垂直につまむ' }, { label: 'b', text: 'なるべく臍に近い部位を垂直につまむ' }, { label: 'c', text: '臍と胸との中間を垂直につまむ' }], correct_choice: 'a', explanation: '腹部は臍から約２cm離れた部位をつまむ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 17 },
  { id: 'q-1b-b-04', category_id: 'cat-1b', body: '皮脂厚測定において垂直につまむのは次のうちどれ', choices: [{ label: 'a', text: '上腕背部' }, { label: 'b', text: '腸骨上部' }, { label: 'c', text: '肩甲骨下筋' }], correct_choice: 'a', explanation: '垂直につまむのは腋窩・上腕背部・腹部・大腿部・下腿内側部', source: 'NEXT TRAINER LAB', is_free: true, display_order: 18 },
  { id: 'q-1b-b-05', category_id: 'cat-1b', body: '大腿部、皮脂厚測定のつまみ方において正しい組み合わせは次のうちどれ①中間 ②内側 ③垂直 ④斜め', choices: [{ label: 'a', text: '①と③' }, { label: 'b', text: '①と④' }, { label: 'c', text: '②と③' }], correct_choice: 'a', explanation: '大腿部の正しいつまみ方は股関節と膝関節の中間を垂直につまむ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 19 },
  { id: 'q-1b-b-06', category_id: 'cat-1b', body: '皮脂厚測定において垂直につまむ組み合わせは次のうちどれ①上腕背部 ②下腿内側部 ③腹部 ④腋窩', choices: [{ label: 'a', text: 'すべて垂直につまむ' }, { label: 'b', text: '②と③と④' }, { label: 'c', text: '①と③と④' }], correct_choice: 'a', explanation: '上腕背部、下腿内側部、腹部、腋窩はすべて垂直につまむ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 20 },
  { id: 'q-1b-b-07', category_id: 'cat-1b', body: '下腿内側部、皮脂厚測定方法において正しいのは次のうちどれ', choices: [{ label: 'a', text: 'クライアントは立ったまま行う' }, { label: 'b', text: 'クライアントの膝を90°曲げてベンチに乗せる' }, { label: 'c', text: 'クライアントの膝を60°曲げてベンチに乗せる' }], correct_choice: 'b', explanation: '下腿内側部の皮脂厚測定方法は膝を90°に曲げてベンチに乗せて行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 21 },
// I-B-c: BMI・体脂肪（10問）
  { id: 'q-1b-c-01', category_id: 'cat-1b', body: '身長158cmの体重54kg、体脂肪率24%の除脂肪体重は次のうちどれ', choices: [{ label: 'a', text: '38kg' }, { label: 'b', text: '36kg' }, { label: 'c', text: '41kg' }], correct_choice: 'c', explanation: '除脂肪体重=体重―体脂肪量54×0.24=12.96 体脂肪量12.96kg54-12.96=41.04 除脂肪体重41kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 22 },
  { id: 'q-1b-c-02', category_id: 'cat-1b', body: '身長185cm体重85kg、体脂肪率35%のクライアントはトレーニングに より体重70kg、体脂肪率26%になった。減少した体脂肪量はどれか', choices: [{ label: 'a', text: '10kg' }, { label: 'b', text: '9kg' }, { label: 'c', text: '11kg' }], correct_choice: 'c', explanation: 'トレーニング前の体脂肪量=85×0.35=29.75トレーニング後の体脂肪量=70×0.26=18.2kg29-18=11 減少した体脂肪量11kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 23 },
  { id: 'q-1b-c-03', category_id: 'cat-1b', body: '身長171cmの体重108kgのクライアントのBMI基準は次のうちどれ', choices: [{ label: 'a', text: '肥満度2' }, { label: 'b', text: '肥満度3' }, { label: 'c', text: '肥満度1' }], correct_choice: 'a', explanation: '1.71×1.71=2.9241 108÷2.9241=36.93.... BMI＝36BMI36は肥満度2になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 24 },
  { id: 'q-1b-c-04', category_id: 'cat-1b', body: '身長165cm、体重75kg、体脂肪率29%のクライアントはトレーニングに より体重67kg、体脂肪率24%になった。減少した体脂肪量はどれか', choices: [{ label: 'a', text: '3kg' }, { label: 'b', text: '8kg' }, { label: 'c', text: '5kg' }], correct_choice: 'c', explanation: '減少した体脂肪量=トレーニング前の体脂肪量-トレーニング後の体脂肪量トレーニング前の体脂肪量=問6参照トレーニング後の体脂肪量=67×0.24=16.08kg21.75-16.08=5.67 減少した体脂肪量5kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 25 },
  { id: 'q-1b-c-05', category_id: 'cat-1b', body: '身長184cmの体重95kgのクライアントのBMIは次のうちどれ', choices: [{ label: 'a', text: '28' }, { label: 'b', text: '23' }, { label: 'c', text: '31' }], correct_choice: 'a', explanation: '1.84×1.84=3.3856 95÷3.3856=28.06... BMI＝28', source: 'NEXT TRAINER LAB', is_free: true, display_order: 26 },
  { id: 'q-1b-c-06', category_id: 'cat-1b', body: '身長165cmの体重75kg、体脂肪率29%の体脂肪量は次のうちどれ', choices: [{ label: 'a', text: '21kg' }, { label: 'b', text: '19kg' }, { label: 'c', text: '17kg' }], correct_choice: 'a', explanation: '体脂肪量=体重×体脂肪率で求められる75×0.29=21.75 体脂肪量21.75kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 27 },
  { id: 'q-1b-c-07', category_id: 'cat-1b', body: '身長178cmの体重69kgのクライアントのBMIは次のうちどれ', choices: [{ label: 'a', text: '23' }, { label: 'b', text: '25' }, { label: 'c', text: '21' }], correct_choice: 'c', explanation: 'BMIは体重(kg)÷（身長(m)×身長(m)）で求められる1.78×1.78=3.1684 69÷3.1684=21.7... BMI＝21', source: 'NEXT TRAINER LAB', is_free: true, display_order: 28 },
  { id: 'q-1b-c-08', category_id: 'cat-1b', body: '身長156cmの体重62kgのクライアントのBMI基準は次のうちどれ', choices: [{ label: 'a', text: '標準' }, { label: 'b', text: '肥満度1' }, { label: 'c', text: '過体重' }], correct_choice: 'c', explanation: '1.56×1.56=2.4336 62÷2.4336=25.47... BMI＝25BMI25は過体重になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 29 },
  { id: 'q-1b-c-09', category_id: 'cat-1b', body: 'BMIの説明として正しいのは次のうちどれ', choices: [{ label: 'a', text: '体格指数' }, { label: 'b', text: '筋肉指数' }, { label: 'c', text: '体脂肪指数' }], correct_choice: 'a', explanation: 'BMIはBody Mass Indexといい体格指数のこと', source: 'NEXT TRAINER LAB', is_free: true, display_order: 30 },
  { id: 'q-1b-c-10', category_id: 'cat-1b', body: '身長158cm、体重54kg、体脂肪率24%のクライアントはトレーニングに より体重48kg、体脂肪率20%になった。減少した体脂肪量はどれか', choices: [{ label: 'a', text: '3kg' }, { label: 'b', text: '8kg' }, { label: 'c', text: '5kg' }], correct_choice: 'a', explanation: 'トレーニング前の体脂肪量=問7参照トレーニング後の体脂肪量=48×0.2=9.6kg12.96-9.6=3.36 減少した体脂肪量3kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 31 },
];
