import { Question } from '../../types';

export const CAT2C_QUESTIONS: Question[] = [
  { id: 'q-2c-a-01', category_id: 'cat-2c', body: '45歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は70%にて行う。クライアントの安静時心拍数は80拍/分\n\n予備心拍数は次のうちどれ', choices: [{ label: 'a', text: '95' }, { label: 'b', text: '90' }, { label: 'c', text: '85' }], correct_choice: 'a', explanation: '予備心拍数＝最大心拍数―安静時心拍数\n最大心拍数＝220―年齢 220-45=175\n175-80=95', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-2c-a-02', category_id: 'cat-2c', body: '45歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は70%にて行う。クライアントの安静時心拍数は80拍/分\n\n目標心拍数は次のうちどれ', choices: [{ label: 'a', text: '145' }, { label: 'b', text: '153' }, { label: 'c', text: '146.5' }], correct_choice: 'c', explanation: '目標心拍数＝予備心拍数×強度＋安静時心拍数\n最大心拍数＝220―年齢 220-45=175\n予備心拍数＝最大心拍数―安静時心拍数\n175-80=95\n95×0.7=66.5 66.5+80=146.5', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-2c-a-03', category_id: 'cat-2c', body: '40歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は80%にて行う。クライアントの安静時心拍数は75拍/分\n\n目標心拍数は次のうちどれ', choices: [{ label: 'a', text: '159' }, { label: 'b', text: '150' }, { label: 'c', text: '157' }], correct_choice: 'a', explanation: '目標心拍数＝予備心拍数×強度＋安静時心拍数\n予備心拍数＝最大心拍数―安静時心拍数\n最大心拍数＝220―年齢 220-40=180\n180-75=105\n105×0.8=84 84+75=159', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-2c-a-04', category_id: 'cat-2c', body: '40歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は80%にて行う。クライアントの安静時心拍数は75拍/分\n\n予備心拍数は次のうちどれ', choices: [{ label: 'a', text: '105' }, { label: 'b', text: '113' }, { label: 'c', text: '110' }], correct_choice: 'a', explanation: '予備心拍数＝最大心拍数―安静時心拍数\n最大心拍数＝220―年齢 220-40=180\n180-75=105', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-2c-a-05', category_id: 'cat-2c', body: '40歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は80%にて行う。クライアントの安静時心拍数は75拍/分\n\n最大心拍数は次のうちどれ', choices: [{ label: 'a', text: '160' }, { label: 'b', text: '170' }, { label: 'c', text: '180' }], correct_choice: 'c', explanation: '最大心拍数＝220―年齢 220-40=180', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-2c-a-06', category_id: 'cat-2c', body: '50歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は70%にて行う。\n目標心拍数は次のうちどれ', choices: [{ label: 'a', text: '120' }, { label: 'b', text: '119' }, { label: 'c', text: '122' }], correct_choice: 'b', explanation: '目標心拍数＝最大心拍数×強度 170×0.7=119', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-2c-a-07', category_id: 'cat-2c', body: '50歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は70%にて行う。\n最大心拍数は次のうちどれ', choices: [{ label: 'a', text: '150' }, { label: 'b', text: '170' }, { label: 'c', text: '160' }], correct_choice: 'b', explanation: '最大心拍数＝220-年齢 220-50=170', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-2c-a-08', category_id: 'cat-2c', body: '45歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は70%にて行う。クライアントの安静時心拍数は80拍/分\n\n最大心拍数は次のうちどれ', choices: [{ label: 'a', text: '165' }, { label: 'b', text: '175' }, { label: 'c', text: '185' }], correct_choice: 'b', explanation: '最大心拍数＝220―年齢 220-45=175', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-2c-a-09', category_id: 'cat-2c', body: '安静時心拍数の情報がない場合、使用する心拍数の求め方は次のうちどれ', choices: [{ label: 'a', text: 'カルボーネン法' }, { label: 'b', text: '最大心拍数法' }, { label: 'c', text: '予備心拍数法' }], correct_choice: 'b', explanation: '安静時心拍数が問題文にない場合は最大心拍数法を使用する。目標心拍数＝最大心拍数×強度', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-2c-a-10', category_id: 'cat-2c', body: '安静時心拍数の情報がある場合、使用する心拍数の求め方は次のうちどれ', choices: [{ label: 'a', text: '最大心拍数法' }, { label: 'b', text: 'カルボーネン法' }, { label: 'c', text: 'どちらでもよい' }], correct_choice: 'b', explanation: '安静時心拍数が問題文にある場合はカルボーネン法を使用する。目標心拍数＝予備心拍数×強度＋安静時心拍数', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-2c-a-11', category_id: 'cat-2c', body: 'カルボーネン法における「予備心拍数」の求め方として正しいのは次のうちどれ', choices: [{ label: 'a', text: '最大心拍数 × 強度' }, { label: 'b', text: '最大心拍数 − 安静時心拍数' }, { label: 'c', text: '220 − 安静時心拍数' }], correct_choice: 'b', explanation: '予備心拍数＝最大心拍数−安静時心拍数。最大心拍数＝220−年齢', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-2c-a-12', category_id: 'cat-2c', body: '30歳のクライアントにて有酸素トレーニングプログラムを組む。\n強度は80%にて行う。\n目標心拍数は次のうちどれ', choices: [{ label: 'a', text: '152' }, { label: 'b', text: '148' }, { label: 'c', text: '160' }], correct_choice: 'a', explanation: '安静時心拍数がないため最大心拍数法を使用。最大心拍数＝220−30＝190。目標心拍数＝190×0.8＝152', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
];
