import { Question } from '../../types';

export const CAT2D_QUESTIONS: Question[] = [
// II-D-a: 高齢者（6問）
  { id: 'q-2d-a-01', category_id: 'cat-2d', body: '高齢者に対する適切なレジスタンストレーニングの強度は次のうちどれ', choices: [{ label: 'a', text: 'RM 30~50%' }, { label: 'b', text: 'RM 55~65%' }, { label: 'c', text: 'RM 60~75%' }], correct_choice: 'c', explanation: '高齢者に対する適切なレジスタンストレーニングの強度はRM 60~75%', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-2d-a-02', category_id: 'cat-2d', body: '高齢者に対する適切なレジスタンストレーニングのレップ数は次のうちどれ', choices: [{ label: 'a', text: '5~10回' }, { label: 'b', text: '10~15回' }, { label: 'c', text: '10~12回' }], correct_choice: 'b', explanation: '高齢者に対する適切なレジスタンストレーニングのレップ数は10~15回', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-2d-a-03', category_id: 'cat-2d', body: '高齢者のトレーニング中、血圧が急激に上昇した場合、適切な対応は次のうちどれ', choices: [{ label: 'a', text: '強度を少しあげる' }, { label: 'b', text: '強度を下げる' }, { label: 'c', text: 'エクササイズを中止する' }], correct_choice: 'b', explanation: '血圧が急激に上昇した場合は強度を下げる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-2d-a-04', category_id: 'cat-2d', body: '高齢者のトレーニング中のRPEとして適切なのは次のうちどれ', choices: [{ label: 'a', text: '楽である' }, { label: 'b', text: 'ややきつい' }, { label: 'c', text: 'きつい' }], correct_choice: 'b', explanation: '高齢者のトレーニング中のRPEとして適切なのは「ややきつい」', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-2d-a-05', category_id: 'cat-2d', body: '高齢者のトレーニング中、血圧が安定している場合、適切な対応は次のうちどれ', choices: [{ label: 'a', text: 'エクササイズを中止する' }, { label: 'b', text: '強度を少しあげる' }, { label: 'c', text: '強度を下げる' }], correct_choice: 'b', explanation: '血圧が安定している場合は強度を少しあげる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-2d-a-06', category_id: 'cat-2d', body: '高齢者に対する下半身のエクササイズとして適切なのは次のうちどれ', choices: [{ label: 'a', text: 'バックスクワット' }, { label: 'b', text: 'レッグプレス' }, { label: 'c', text: 'フロントスクワット' }], correct_choice: 'b', explanation: '高齢者に対する下半身のエクササイズとして適切なのはレッグプレス', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
// II-D-b: 妊婦（5問）
  { id: 'q-2d-b-01', category_id: 'cat-2d', body: '仰臥位のエクササイズを避けるべきなのはいつからか', choices: [{ label: 'a', text: '妊娠した時' }, { label: 'b', text: '妊娠から6ヶ月後' }, { label: 'c', text: '妊娠から3ヶ月後' }], correct_choice: 'a', explanation: '仰臥位のエクササイズは妊娠した時から避けるべき', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-2d-b-02', category_id: 'cat-2d', body: '妊婦に対して避けるべきエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'ペックデック' }, { label: 'b', text: 'マシンチェストプレス' }, { label: 'c', text: 'ライイング・ニー・ツー・チェスト' }], correct_choice: 'c', explanation: 'ライイング・ニー・ツー・チェストは仰臥位のため妊婦には避けるべき', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-2d-b-03', category_id: 'cat-2d', body: '妊婦に対して適切なエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'ランジウォーク' }, { label: 'b', text: 'レッグエクステンション' }, { label: 'c', text: 'プランク' }], correct_choice: 'b', explanation: '妊婦に対して適切なエクササイズはレッグエクステンション', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-2d-b-04', category_id: 'cat-2d', body: '妊婦が最も必要としている栄養素は次のうちどれ', choices: [{ label: 'a', text: 'タンパク質' }, { label: 'b', text: '炭水化物' }, { label: 'c', text: '脂質' }], correct_choice: 'b', explanation: '妊婦が最も必要としている栄養素は炭水化物', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-2d-b-05', category_id: 'cat-2d', body: '妊婦のトレーニング強度を測るために適切なのは次のうちどれ', choices: [{ label: 'a', text: 'vo2max' }, { label: 'b', text: 'RPE' }, { label: 'c', text: 'METs' }], correct_choice: 'b', explanation: '妊婦のトレーニング強度を測るために適切なのはRPE', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
// II-D-c: 子ども（6問）
  { id: 'q-2d-c-01', category_id: 'cat-2d', body: '子どものレジスタンストレーニングにて怪我のリスクが高い最大の原因は次のうちどれ', choices: [{ label: 'a', text: '成長期による事' }, { label: 'b', text: '有資格者のトレーニング指導者がいない' }, { label: 'c', text: '骨密度が低い' }], correct_choice: 'b', explanation: '子どものレジスタンストレーニングにて怪我のリスクが高い最大の原因は有資格者のトレーニング指導者がいないこと', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-2d-c-02', category_id: 'cat-2d', body: '子どものレジスタンストレーニングにて筋力向上のメカニズムは次のうちどれ', choices: [{ label: 'a', text: '筋肥大' }, { label: 'b', text: '神経伝達の上昇' }, { label: 'c', text: '筋繊維の増加' }], correct_choice: 'b', explanation: '子どものレジスタンストレーニングにて筋力向上のメカニズムは神経伝達の上昇', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-2d-c-03', category_id: 'cat-2d', body: '子どものレジスタンストレーニングにて推奨されるものは次のうちどれ\n①1RMテストは行ってもよい ②マシントレーニングは推奨されない ③オリンピックリフティングの派生種目は推奨される ④大人のプログラムを少量にして行う', choices: [{ label: 'a', text: '①と④' }, { label: 'b', text: '②と③' }, { label: 'c', text: '①と④' }], correct_choice: 'a', explanation: '子どものレジスタンストレーニングにて1RMテストは行ってもよく、大人のプログラムを少量にして行うことが推奨される', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-2d-c-04', category_id: 'cat-2d', body: '子どものレジスタンストレーニングにて推奨されるものは次のうちどれ\n①バルサルバ法を用いて行う ②セット間の休息は1分以上にする ③トレーニング前にウォームアップを行う ④バリスティックなトレーニングを行う', choices: [{ label: 'a', text: '①と③' }, { label: 'b', text: '②と④' }, { label: 'c', text: '②と③' }], correct_choice: 'c', explanation: '子どものレジスタンストレーニングにてセット間の休息は1分以上にし、トレーニング前にウォームアップを行うことが推奨される', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-2d-c-05', category_id: 'cat-2d', body: '子どものレジスタンストレーニングにて正しくないものは次のうちどれ', choices: [{ label: 'a', text: '8~15回を1~3セット行う' }, { label: 'b', text: '重量が最重要' }, { label: 'c', text: 'トレーニングを行った際は必ず休息日を設ける' }], correct_choice: 'b', explanation: '子どものレジスタンストレーニングにて重量が最重要ではない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },
  { id: 'q-2d-c-06', category_id: 'cat-2d', body: '子どもの有酸素トレーニングとして適切なのは次のうちどれ', choices: [{ label: 'a', text: '長距離走' }, { label: 'b', text: 'サーキットトレーニング' }, { label: 'c', text: 'レジスタンストレーニング' }], correct_choice: 'b', explanation: '子どもの有酸素トレーニングとして適切なのはサーキットトレーニング', source: 'NEXT TRAINER LAB', is_free: true, display_order: 17 },
// II-D-d: その他のクライアント（15問）
  { id: 'q-2d-d-01', category_id: 'cat-2d', body: 'メタボリックシンドロームの基準値として正しいのは次のうちどれ', choices: [{ label: 'a', text: '男性：ウエスト105cm' }, { label: 'b', text: '男性：ウエスト102cm' }, { label: 'c', text: '男性：ウエスト100cm' }], correct_choice: 'b', explanation: 'メタボリックシンドロームの基準値として男性はウエスト102cm', source: 'NEXT TRAINER LAB', is_free: true, display_order: 18 },
  { id: 'q-2d-d-02', category_id: 'cat-2d', body: '腰痛を持つクライアントに対して、強化すべき筋群は次のうちどれ', choices: [{ label: 'a', text: '股関節伸展筋群' }, { label: 'b', text: '股関節屈曲筋群' }, { label: 'c', text: '股関節外転筋群' }], correct_choice: 'b', explanation: '腰痛を持つクライアントに対して強化すべき筋群は股関節屈曲筋群', source: 'NEXT TRAINER LAB', is_free: true, display_order: 19 },
  { id: 'q-2d-d-03', category_id: 'cat-2d', body: '肩のインピンジメントに対して、強化すべきエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'サイドレイズ' }, { label: 'b', text: 'エクスターナルローテーション' }, { label: 'c', text: 'インターナルローテーション' }], correct_choice: 'b', explanation: '肩のインピンジメントに対して強化すべきエクササイズはエクスターナルローテーション', source: 'NEXT TRAINER LAB', is_free: true, display_order: 20 },
  { id: 'q-2d-d-04', category_id: 'cat-2d', body: '肩のインピンジメントに対して、避けるべきエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'サイドレイズ' }, { label: 'b', text: 'インターナルローテーション' }, { label: 'c', text: 'エクスターナルローテーション' }], correct_choice: 'a', explanation: '肩のインピンジメントに対して避けるべきエクササイズはサイドレイズ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 21 },
  { id: 'q-2d-d-05', category_id: 'cat-2d', body: '肩関節の後方が硬い場合、ストレッチすべきは次のうちどれ', choices: [{ label: 'a', text: 'インターナルローテーション' }, { label: 'b', text: 'サイドレイズ' }, { label: 'c', text: 'エクスターナルローテーション' }], correct_choice: 'c', explanation: '肩関節の後方が硬い場合、ストレッチすべきはエクスターナルローテーション', source: 'NEXT TRAINER LAB', is_free: true, display_order: 22 },
  { id: 'q-2d-d-06', category_id: 'cat-2d', body: '過食症の特徴として正しいのは次のうちどれ', choices: [{ label: 'a', text: '大量に食べることを繰り返す' }, { label: 'b', text: '食べ物について常に考えている' }, { label: 'c', text: '体重の増加を常に拒絶する' }], correct_choice: 'a', explanation: '過食症の特徴として正しいのは大量に食べることを繰り返すこと', source: 'NEXT TRAINER LAB', is_free: true, display_order: 23 },
  { id: 'q-2d-d-07', category_id: 'cat-2d', body: '摂食障害が疑われるクライアントに対して、適切な対応は次のうちどれ', choices: [{ label: 'a', text: 'トレーニングを開始する' }, { label: 'b', text: '医師の診断を受けてもらう' }, { label: 'c', text: '強度を落としてトレーニングを開始する' }], correct_choice: 'b', explanation: '摂食障害が疑われるクライアントに対して適切な対応は医師の診断を受けてもらうこと', source: 'NEXT TRAINER LAB', is_free: true, display_order: 24 },
  { id: 'q-2d-d-08', category_id: 'cat-2d', body: 'メタボリックシンドロームの診断基準として正しい組み合わせは次のうちどれ', choices: [{ label: 'a', text: '男性：ウエスト105cm 血圧130/80mmHg 空腹時血糖110mg/dl' }, { label: 'b', text: '女性：ウエスト80cm トリグリセリド150mg/dl 低HDL40mg/dl' }, { label: 'c', text: '女性：ウエスト88cm 低HDL50mg/dl 空腹時血糖100mg/dl' }], correct_choice: 'c', explanation: 'メタボリックシンドロームの診断基準として正しい組み合わせは女性：ウエスト88cm 低HDL50mg/dl 空腹時血糖100mg/dl', source: 'NEXT TRAINER LAB', is_free: true, display_order: 25 },
  { id: 'q-2d-d-09', category_id: 'cat-2d', body: 'メタボリックシンドロームの基準値として正しいのは次のうちどれ', choices: [{ label: 'a', text: '男性：低HDL 50mg/dl' }, { label: 'b', text: '男性：低HDL 45mg/dl' }, { label: 'c', text: '男性：低HDL 40mg/dl' }], correct_choice: 'c', explanation: 'メタボリックシンドロームの基準値として男性は低HDL 40mg/dl', source: 'NEXT TRAINER LAB', is_free: true, display_order: 26 },
  { id: 'q-2d-d-10', category_id: 'cat-2d', body: '拒食症の特徴として正しいのは次のうちどれ', choices: [{ label: 'a', text: '体重を維持することへの拒絶' }, { label: 'b', text: '自己誘発性嘔吐する' }, { label: 'c', text: 'カロリー燃焼のための異常な運動を行う' }], correct_choice: 'a', explanation: '拒食症の特徴として正しいのは体重を維持することへの拒絶', source: 'NEXT TRAINER LAB', is_free: true, display_order: 27 },
  { id: 'q-2d-d-11', category_id: 'cat-2d', body: '肩関節の前方が硬い場合、ストレッチすべきは次のうちどれ', choices: [{ label: 'a', text: 'インターナルローテーション' }, { label: 'b', text: 'エクスターナルローテーション' }, { label: 'c', text: 'サイドレイズ' }], correct_choice: 'a', explanation: '肩関節の前方が硬い場合、ストレッチすべきはインターナルローテーション', source: 'NEXT TRAINER LAB', is_free: true, display_order: 28 },
  { id: 'q-2d-d-12', category_id: 'cat-2d', body: 'むちゃ食い障害の特徴として正しいのは次のうちどれ', choices: [{ label: 'a', text: '体重を維持することへの拒絶する' }, { label: 'b', text: '歪んだ身体イメージを持っている' }, { label: 'c', text: '食事量をコントロールできず、大量の食事をする' }], correct_choice: 'c', explanation: 'むちゃ食い障害の特徴として正しいのは食事量をコントロールできず、大量の食事をすること', source: 'NEXT TRAINER LAB', is_free: true, display_order: 29 },
  { id: 'q-2d-d-13', category_id: 'cat-2d', body: '糖尿病クライアントに対して適切なプログラムの数値を選べ\nタンパク質を体重1kgあたり①＿gを1日に摂取し、②＿分以上の有酸素運動を行う', choices: [{ label: 'a', text: '①1.8　②10~15' }, { label: 'b', text: '①1.5　②10~20' }, { label: 'c', text: '①1.8　②15~20' }], correct_choice: 'c', explanation: '糖尿病クライアントに対してタンパク質を体重1kgあたり1.8gを1日に摂取し、15~20分以上の有酸素運動を行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 30 },
  { id: 'q-2d-d-14', category_id: 'cat-2d', body: '女性アスリートの三主徴に含まれないものは次のうちどれ', choices: [{ label: 'a', text: '骨粗鬆症' }, { label: 'b', text: '無月経' }, { label: 'c', text: '低血糖' }], correct_choice: 'c', explanation: '女性アスリートの三主徴は摂食障害・無月経・骨粗鬆症であり、低血糖は含まれない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 31 },
  { id: 'q-2d-d-15', category_id: 'cat-2d', body: '肩のインピンジメントに対して、避けるべきエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'バイセップスカール' }, { label: 'b', text: 'ラテラルレイズ' }, { label: 'c', text: 'トライセプスプレスダウン' }], correct_choice: 'b', explanation: '肩のインピンジメントに対して避けるべきエクササイズはラテラルレイズ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 32 },
];
