import { Question } from '../../types';

export const CAT2A_QUESTIONS: Question[] = [
// II-A-a: プランニング（16問）
  { id: 'q-2a-a-01', category_id: 'cat-2a', body: '上級者で筋パワーが目的の場合、適切なセット数は次のうちどれ。', choices: [{ label: 'a', text: '1セット' }, { label: 'b', text: '3セット' }, { label: 'c', text: '2セット' }], correct_choice: 'b', explanation: '上級者で筋パワーが目的の場合、適切なセット数は3~6セット', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-2a-a-02', category_id: 'cat-2a', body: '単関節種目において筋肥大が目的の場合、適切な休息時間は次のうちどれ。', choices: [{ label: 'a', text: '30~90秒' }, { label: 'b', text: '60~90秒' }, { label: 'c', text: '30秒以下' }], correct_choice: 'b', explanation: '単関節種目の筋肥大が目的の場合、適切な休息時間は60~90秒', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-2a-a-03', category_id: 'cat-2a', body: 'トレーニング歴が5 ヶ月のクライアントの適切なレベルは次のうちどれ。', choices: [{ label: 'a', text: '初心者' }, { label: 'b', text: '上級者' }, { label: 'c', text: '中級者' }], correct_choice: 'a', explanation: '6ヶ月以上から中級者となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-2a-a-04', category_id: 'cat-2a', body: '中級者のトレーニングの頻度として、適切なのは次のうちどれ。', choices: [{ label: 'a', text: '2~4 回/週' }, { label: 'b', text: '4 回/週' }, { label: 'c', text: '4 回/週（スプリットルーティン）' }], correct_choice: 'c', explanation: '中級者のトレーニングの頻度として、適切なのは 3回（全身）4回(スプリットルーティン)/週', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-2a-a-05', category_id: 'cat-2a', body: '初級者のトレーニングの頻度として、適切なのは次のうちどれ。', choices: [{ label: 'a', text: '2~3 回/週' }, { label: 'b', text: '4~5 回/週' }, { label: 'c', text: '3~4 回/週' }], correct_choice: 'a', explanation: '初級者のトレーニングの頻度として、適切なのは2~3回/週', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-2a-a-06', category_id: 'cat-2a', body: '初心者で筋持久力が目的の場合適切なレップ数は次のうちどれ', choices: [{ label: 'a', text: '10~15RM' }, { label: 'b', text: '10~30RM' }, { label: 'c', text: '10~20RM' }], correct_choice: 'a', explanation: '初心者で筋持久力が目的の場合、適切なレップ数は10~15RM', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-2a-a-07', category_id: 'cat-2a', body: '初心者で筋肥大が目的の場合、適切なセット数は次のうちどれ。', choices: [{ label: 'a', text: '1~3セット' }, { label: 'b', text: '1セットのみ' }, { label: 'c', text: '3セット以上' }], correct_choice: 'a', explanation: '初心者で筋肥大が目的の場合、適切なセット数は1~3セット', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-2a-a-08', category_id: 'cat-2a', body: '中級者で筋パワーが目的の場合、適切なレップ数は次のうちどれ。', choices: [{ label: 'a', text: '1RM' }, { label: 'b', text: '2RM' }, { label: 'c', text: '3RM' }], correct_choice: 'c', explanation: '中級者で筋パワーが目的の場合、適切なレップ数は3~6RM', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-2a-a-09', category_id: 'cat-2a', body: '中級者で筋力が目的の場合適切なレップ数は次のうちどれ', choices: [{ label: 'a', text: '6RM以下' }, { label: 'b', text: '2~6RM' }, { label: 'c', text: '3~6RM' }], correct_choice: 'c', explanation: '中級者で筋力が目的の場合、適切なレップ数は3~6RM', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-2a-a-10', category_id: 'cat-2a', body: 'トレーニング歴が1 年3 ヶ月のクライアントの適切なレベルはどれ。', choices: [{ label: 'a', text: '初心者' }, { label: 'b', text: '中級者' }, { label: 'c', text: '上級者' }], correct_choice: 'c', explanation: '1年以上トレーニング歴があるので上級者となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-2a-a-11', category_id: 'cat-2a', body: '筋力が目的の場合、適切な休息時間は次のうちどれ。', choices: [{ label: 'a', text: '1~2 分' }, { label: 'b', text: '2~3 分' }, { label: 'c', text: '2~5 分' }], correct_choice: 'c', explanation: '筋力が目的の場合、適切な休息時間は2~5分', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-2a-a-12', category_id: 'cat-2a', body: '上級者で筋肥大が目的の場合、適切なレップ数は次のうちどれ。', choices: [{ label: 'a', text: '8~35RM以上' }, { label: 'b', text: '5~30RM以上' }, { label: 'c', text: '8~30RM以上' }], correct_choice: 'b', explanation: '上級者で筋肥大が目的の場合、適切なレップ数は5~30RM', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-2a-a-13', category_id: 'cat-2a', body: '初心者で筋力が目的の場合、適切なレップ数は次のうちどれ。', choices: [{ label: 'a', text: '12RM' }, { label: 'b', text: '15RM' }, { label: 'c', text: '5RM' }], correct_choice: 'c', explanation: '初心者で筋力が目的の場合、適切なレップ数は6RM以下', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-2a-a-14', category_id: 'cat-2a', body: '中級者で筋力が目的の場合、適切なセット数は次のうちどれ。', choices: [{ label: 'a', text: '3セット' }, { label: 'b', text: '2セット' }, { label: 'c', text: '1セット' }], correct_choice: 'a', explanation: '中級者で筋力が目的の場合、適切なセット数は3セット以上', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-2a-a-15', category_id: 'cat-2a', body: '多関節種目において筋肥大が目的の場合、適切な休息時間は次のうちどれ', choices: [{ label: 'a', text: '1~2分以上' }, { label: 'b', text: '1~3分以上' }, { label: 'c', text: '2~3分以上' }], correct_choice: 'c', explanation: '多関節種目の筋肥大が目的の場合、適切な休息時間は2~3分以上', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-2a-a-16', category_id: 'cat-2a', body: '上級者で筋持久力が目的の場合、適切なレップ数は次のうちどれ。', choices: [{ label: 'a', text: '10~30RM' }, { label: 'b', text: '15~30RM' }, { label: 'c', text: '15~30RM以上' }], correct_choice: 'c', explanation: '上級者で筋持久力が目的の場合、適切なレップ数は15~30RM以上', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },
];
