import { Question } from '../../types';

export const CAT2B_QUESTIONS: Question[] = [
  { id: 'q-2b-a-01', category_id: 'cat-2b', body: 'エクササイズを8回行うのが可能なのは、1RMが何％の負荷のときか', choices: [{ label: 'a', text: '85%' }, { label: 'b', text: '90%' }, { label: 'c', text: '80%' }], correct_choice: 'c', explanation: '8レップ＝80%の負荷', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-2b-a-02', category_id: 'cat-2b', body: 'エクササイズを11回行うのが可能なのは、1RMが何％の負荷のときか', choices: [{ label: 'a', text: '70%' }, { label: 'b', text: '75%' }, { label: 'c', text: '65%' }], correct_choice: 'a', explanation: '11レップ＝70%の負荷', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-2b-a-03', category_id: 'cat-2b', body: 'エクササイズを4回行うのが可能なのは、1RMが何％の負荷のときか', choices: [{ label: 'a', text: '90%' }, { label: 'b', text: '85%' }, { label: 'c', text: '80%' }], correct_choice: 'a', explanation: '4レップ＝90%の負荷', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-2b-a-04', category_id: 'cat-2b', body: 'エクササイズを15回行うのが可能なのは、1RMが何％の負荷のときか', choices: [{ label: 'a', text: '60%' }, { label: 'b', text: '65%' }, { label: 'c', text: '70%' }], correct_choice: 'b', explanation: '15レップ＝65%の負荷', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-2b-a-05', category_id: 'cat-2b', body: '1RMが90kgの場合、8レップの負荷は次のうちどれ', choices: [{ label: 'a', text: '76kg' }, { label: 'b', text: '72kg' }, { label: 'c', text: '70kg' }], correct_choice: 'b', explanation: '1RM＝90kg、8レップ＝80%。90×0.80＝72kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-2b-a-06', category_id: 'cat-2b', body: '1RMが70kgの場合、11レップの負荷は次のうちどれ', choices: [{ label: 'a', text: '52kg' }, { label: 'b', text: '49kg' }, { label: 'c', text: '50kg' }], correct_choice: 'b', explanation: '1RM＝70kg、11レップ＝70%。70×0.70＝49kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-2b-a-07', category_id: 'cat-2b', body: '8RMが80kgの場合、1レップの負荷は次のうちどれ', choices: [{ label: 'a', text: '105kg' }, { label: 'b', text: '100kg' }, { label: 'c', text: '95kg' }], correct_choice: 'b', explanation: '80kgを8回上げているということは80%の負荷を持てている。1RM＝80÷0.8＝100kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-2b-a-08', category_id: 'cat-2b', body: '4RMが60kgの場合、1レップの負荷は次のうちどれ', choices: [{ label: 'a', text: '55kg' }, { label: 'b', text: '66kg' }, { label: 'c', text: '70kg' }], correct_choice: 'b', explanation: '60kgを4回上げているということは90%の負荷を持てている。1RM＝60÷0.9＝66kg（小数点以下切り捨て）', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-2b-a-09', category_id: 'cat-2b', body: '15RMが30kgの場合、1レップの負荷は次のうちどれ', choices: [{ label: 'a', text: '42kg' }, { label: 'b', text: '40kg' }, { label: 'c', text: '46kg' }], correct_choice: 'c', explanation: '30kgを15回上げているということは65%の負荷を持てている。1RM＝30÷0.65≒46kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-2b-a-10', category_id: 'cat-2b', body: 'エクササイズを6回行うのが可能なのは、1RMが何％の負荷のときか', choices: [{ label: 'a', text: '80%' }, { label: 'b', text: '85%' }, { label: 'c', text: '90%' }], correct_choice: 'b', explanation: '6レップ＝85%の負荷', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-2b-a-11', category_id: 'cat-2b', body: 'エクササイズを10回行うのが可能なのは、1RMが何％の負荷のときか', choices: [{ label: 'a', text: '70%' }, { label: 'b', text: '80%' }, { label: 'c', text: '75%' }], correct_choice: 'c', explanation: '10レップ＝75%の負荷', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-2b-a-12', category_id: 'cat-2b', body: 'エクササイズを2回行うのが可能なのは、1RMが何％の負荷のときか', choices: [{ label: 'a', text: '95%' }, { label: 'b', text: '90%' }, { label: 'c', text: '100%' }], correct_choice: 'a', explanation: '2レップ＝95%の負荷', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-2b-a-13', category_id: 'cat-2b', body: '1RMが100kgの場合、6レップの負荷は次のうちどれ', choices: [{ label: 'a', text: '80kg' }, { label: 'b', text: '85kg' }, { label: 'c', text: '90kg' }], correct_choice: 'b', explanation: '1RM＝100kg、6レップ＝85%。100×0.85＝85kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-2b-a-14', category_id: 'cat-2b', body: '6RMが51kgの場合、1RMの負荷は次のうちどれ', choices: [{ label: 'a', text: '55kg' }, { label: 'b', text: '60kg' }, { label: 'c', text: '65kg' }], correct_choice: 'b', explanation: '51kgを6回上げているということは85%の負荷を持てている。1RM＝51÷0.85＝60kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-2b-a-15', category_id: 'cat-2b', body: '10RMが60kgの場合、1RMの負荷は次のうちどれ', choices: [{ label: 'a', text: '75kg' }, { label: 'b', text: '85kg' }, { label: 'c', text: '80kg' }], correct_choice: 'c', explanation: '60kgを10回上げているということは75%の負荷を持てている。1RM＝60÷0.75＝80kg', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
];
