import { Question } from '../../types';

export const CAT3G_QUESTIONS: Question[] = [
// III-G-a: 筋構造・繊維（7問）
  { id: 'q-3g-a-01', category_id: 'cat-3g', body: 'スクワットにてバーベルを下ろしている時、ハムストリングスが短縮性の筋活動のとき、H帯はどうなるか', choices: [{ label: 'a', text: '短くなる' }, { label: 'b', text: '変わらない' }, { label: 'c', text: '長くなる' }], correct_choice: 'a', explanation: 'スクワットのバーベルを下ろしている時ハムストリングスは短縮性収縮時になるため', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-3g-a-02', category_id: 'cat-3g', body: '筋が収縮した時、長さが変わらない帯はどれか', choices: [{ label: 'a', text: 'I帯' }, { label: 'b', text: 'A帯' }, { label: 'c', text: 'H帯' }], correct_choice: 'b', explanation: 'A帯（暗帯）はミオシンフィラメントの長さで決まるため、収縮しても長さは変わらない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-3g-a-03', category_id: 'cat-3g', body: '骨粗鬆症に効果が一番高いエクササイズの筋活動はどれか', choices: [{ label: 'a', text: 'エキセントリック' }, { label: 'b', text: 'コンセントリック' }, { label: 'c', text: 'アイソメトリック' }], correct_choice: 'a', explanation: 'エキセントリックは骨への刺激が最も大きく、骨密度向上に効果が高い', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-3g-a-04', category_id: 'cat-3g', body: 'クロスブリッジと結合するフィラメントはどれか', choices: [{ label: 'a', text: 'アクチン' }, { label: 'b', text: 'ミオシン' }, { label: 'c', text: 'トロポニン' }], correct_choice: 'a', explanation: 'クロスブリッジ（ミオシン頭部）はアクチンフィラメントと結合する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-3g-a-05', category_id: 'cat-3g', body: '筋が収縮したときに中央に引き寄せられるのはどれか', choices: [{ label: 'a', text: 'A帯' }, { label: 'b', text: 'H帯' }, { label: 'c', text: 'Z線' }], correct_choice: 'c', explanation: '筋収縮時にアクチンフィラメントが滑り込むことでZ線が中央に引き寄せられる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-3g-a-06', category_id: 'cat-3g', body: '筋で最小のものはどれか', choices: [{ label: 'a', text: '筋原繊維' }, { label: 'b', text: 'フィラメント' }, { label: 'c', text: '筋繊維' }], correct_choice: 'b', explanation: 'フィラメント（アクチン・ミオシン）は筋の最小構造である', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-3g-a-07', category_id: 'cat-3g', body: 'カルシウムイオンを貯蔵しているのはどれか', choices: [{ label: 'a', text: '筋小胞体' }, { label: 'b', text: 'ミトコンドリア' }, { label: 'c', text: 'ゴルジ体' }], correct_choice: 'a', explanation: '筋小胞体がカルシウムイオンを貯蔵・放出し、筋収縮を制御する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },

// III-G-b: 筋繊維タイプ（9問）
  { id: 'q-3g-b-01', category_id: 'cat-3g', body: '速筋ではないものはどれか', choices: [{ label: 'a', text: 'タイプⅡx' }, { label: 'b', text: 'タイプⅠ' }, { label: 'c', text: 'タイプⅡA' }], correct_choice: 'b', explanation: 'タイプⅠは遅筋（酸化性）であり速筋ではない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-3g-b-02', category_id: 'cat-3g', body: 'ミオグロビンが最も多い筋繊維タイプはどれか', choices: [{ label: 'a', text: 'タイプⅠ' }, { label: 'b', text: 'タイプⅡA' }, { label: 'c', text: 'タイプⅡx' }], correct_choice: 'a', explanation: 'タイプⅠ（遅筋）はミオグロビンが最も多く、酸素を多く貯蔵できる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-3g-b-03', category_id: 'cat-3g', body: 'タイプⅡxの特徴はどれか', choices: [{ label: 'a', text: '収縮速度が遅く持久力が高い' }, { label: 'b', text: '収縮速度が遅く持久力は低い' }, { label: 'c', text: '収縮速度が早く持久力は低い' }], correct_choice: 'c', explanation: 'タイプⅡx（速筋）は収縮速度が最も速いが、持久力は最も低い', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-3g-b-04', category_id: 'cat-3g', body: '収縮速度が最も速い筋繊維タイプはどれか', choices: [{ label: 'a', text: 'タイプⅠ' }, { label: 'b', text: 'タイプⅡA' }, { label: 'c', text: 'タイプⅡx' }], correct_choice: 'c', explanation: 'タイプⅡxは収縮速度が最も速い', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-3g-b-05', category_id: 'cat-3g', body: '収縮力が最も強い筋繊維タイプはどれか', choices: [{ label: 'a', text: 'タイプⅠ' }, { label: 'b', text: 'タイプⅡA' }, { label: 'c', text: 'タイプⅡx' }], correct_choice: 'c', explanation: 'タイプⅡxは収縮力が最も強い', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-3g-b-06', category_id: 'cat-3g', body: 'ミトコンドリアが最も多い筋繊維タイプはどれか', choices: [{ label: 'a', text: 'タイプⅠ' }, { label: 'b', text: 'タイプⅡA' }, { label: 'c', text: 'タイプⅡx' }], correct_choice: 'a', explanation: 'タイプⅠ（遅筋）はミトコンドリアが最も多く、有酸素的なエネルギー産生に優れる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-3g-b-07', category_id: 'cat-3g', body: '毛細血管密度が最も高い筋繊維タイプはどれか', choices: [{ label: 'a', text: 'タイプⅠ' }, { label: 'b', text: 'タイプⅡA' }, { label: 'c', text: 'タイプⅡx' }], correct_choice: 'a', explanation: 'タイプⅠ（遅筋）は毛細血管密度が最も高い', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-3g-b-08', category_id: 'cat-3g', body: '持久力が最も低い筋繊維タイプはどれか', choices: [{ label: 'a', text: 'タイプⅠ' }, { label: 'b', text: 'タイプⅡA' }, { label: 'c', text: 'タイプⅡx' }], correct_choice: 'c', explanation: 'タイプⅡxは持久力が最も低い', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-3g-b-09', category_id: 'cat-3g', body: 'エネルギー源が脂肪と糖質の筋繊維タイプはどれか', choices: [{ label: 'a', text: 'タイプⅡA' }, { label: 'b', text: 'タイプⅠ' }, { label: 'c', text: 'タイプⅡx' }], correct_choice: 'a', explanation: 'タイプⅡA（中間筋）は脂肪と糖質の両方をエネルギー源とする', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },

// III-G-c: バイオメカニクス/てこの原理（9問）
  { id: 'q-3g-c-01', category_id: 'cat-3g', body: '腓腹筋に効果的なエクササイズはどれか', choices: [{ label: 'a', text: 'スタンディングカーフレイズ' }, { label: 'b', text: 'シーテッドカーフレイズ' }, { label: 'c', text: 'レッグプレス' }], correct_choice: 'a', explanation: 'スタンディングカーフレイズは膝伸展位で行うため腓腹筋に効果的', source: 'NEXT TRAINER LAB', is_free: true, display_order: 17 },
  { id: 'q-3g-c-02', category_id: 'cat-3g', body: '第二のてこに当てはまるエクササイズはどれか', choices: [{ label: 'a', text: 'バイセップスカール' }, { label: 'b', text: 'カーフレイズ' }, { label: 'c', text: 'トライセプスプッシュダウン' }], correct_choice: 'b', explanation: 'カーフレイズは第二のてこ（支点-抵抗-力点の順）に分類される', source: 'NEXT TRAINER LAB', is_free: true, display_order: 18 },
  { id: 'q-3g-c-03', category_id: 'cat-3g', body: 'ヒラメ筋に効果的なエクササイズはどれか', choices: [{ label: 'a', text: 'スタンディングカーフレイズ' }, { label: 'b', text: 'レッグプレス' }, { label: 'c', text: 'シーテッドカーフレイズ' }], correct_choice: 'c', explanation: 'シーテッドカーフレイズは膝屈曲位で行うためヒラメ筋に効果的', source: 'NEXT TRAINER LAB', is_free: true, display_order: 19 },
  { id: 'q-3g-c-04', category_id: 'cat-3g', body: '第一のてこに当てはまるエクササイズはどれか', choices: [{ label: 'a', text: 'トライセプスエクステンション' }, { label: 'b', text: 'バイセップスカール' }, { label: 'c', text: 'トライセプスプッシュダウン' }], correct_choice: 'a', explanation: 'トライセプスエクステンションは第一のてこ（力点-支点-抵抗の順）に分類される', source: 'NEXT TRAINER LAB', is_free: true, display_order: 20 },
  { id: 'q-3g-c-05', category_id: 'cat-3g', body: '平泳ぎのキャッチ動作で主に働く筋肉はどれか', choices: [{ label: 'a', text: '広背筋' }, { label: 'b', text: '三角筋' }, { label: 'c', text: '上腕二頭筋' }], correct_choice: 'a', explanation: '平泳ぎのキャッチ動作では広背筋が主に働く', source: 'NEXT TRAINER LAB', is_free: true, display_order: 21 },
  { id: 'q-3g-c-06', category_id: 'cat-3g', body: '抗力より少ない筋力で動かせるてこはどれか', choices: [{ label: 'a', text: '第二のてこ' }, { label: 'b', text: '第一のてこ' }, { label: 'c', text: '第三のてこ' }], correct_choice: 'a', explanation: '第二のてこは力点から支点までの距離が長いため、抗力より少ない筋力で動かせる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 22 },
  { id: 'q-3g-c-07', category_id: 'cat-3g', body: '砲丸投げに似たエクササイズの組み合わせはどれか', choices: [{ label: 'a', text: 'ベンチプレス/ラットプルダウン' }, { label: 'b', text: 'デッドリフト/レッグカール' }, { label: 'c', text: 'ショルダープレス/フロントランジ' }], correct_choice: 'c', explanation: '砲丸投げは上半身の押す動作と下半身の前方への動作を含み、ショルダープレスとフロントランジが類似する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 23 },
  { id: 'q-3g-c-08', category_id: 'cat-3g', body: '遅発性筋肉痛の原因となる筋活動はどれか', choices: [{ label: 'a', text: 'エキセントリック' }, { label: 'b', text: 'コンセントリック' }, { label: 'c', text: 'アイソメトリック' }], correct_choice: 'a', explanation: 'エキセントリック（伸張性）筋活動が遅発性筋肉痛（DOMS）の主な原因となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 24 },
  { id: 'q-3g-c-09', category_id: 'cat-3g', body: '第三のてこに当てはまるエクササイズはどれか', choices: [{ label: 'a', text: 'バイセップスカール' }, { label: 'b', text: 'カーフレイズ' }, { label: 'c', text: 'ハンマーカール' }], correct_choice: 'a', explanation: 'バイセップスカールは第三のてこ（支点-力点-抵抗の順）に分類される', source: 'NEXT TRAINER LAB', is_free: true, display_order: 25 },
];
