import { Question } from '../../types';

export const CAT3B_QUESTIONS: Question[] = [
// III-B-a: 補助（13問）
  { id: 'q-3b-a-01', category_id: 'cat-3b', body: 'パワークリーンの補助の仕方として、正しいのは次のうちどれ', choices: [{ label: 'a', text: '補助は必要ない' }, { label: 'b', text: 'バーベルを落とさないように拳上者の後ろで支える' }, { label: 'c', text: '両端に１人ずつと後ろに１人で補助をする' }], correct_choice: 'a', explanation: 'パワーエクササイズの補助は必要ない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-3b-a-02', category_id: 'cat-3b', body: '補助が必要ない種目は次のうちどれ', choices: [{ label: 'a', text: 'デットリフト' }, { label: 'b', text: 'スクワット' }, { label: 'c', text: 'ベンチプレス' }], correct_choice: 'a', explanation: 'デットリフトは補助の対象とならないため', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-3b-a-03', category_id: 'cat-3b', body: 'スクワットの補助の仕方として、正しいものは次のうちどれ', choices: [{ label: 'a', text: 'バーベルを常にもち補助をする' }, { label: 'b', text: '両端に１人ずつと後ろに１人で補助をする' }, { label: 'c', text: '常に後ろに付き補助をする' }], correct_choice: 'b', explanation: 'スクワットやランジといった種目は、基本３人での補助となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-3b-a-04', category_id: 'cat-3b', body: '補助が一番必要な種目は次のうちどれ', choices: [{ label: 'a', text: 'トライセプスプッシュダウン' }, { label: 'b', text: 'フロントスクワット' }, { label: 'c', text: 'ベンチプレス' }], correct_choice: 'c', explanation: 'フロントスクワットはバーベルを前に落とす事で回避することができる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-3b-a-05', category_id: 'cat-3b', body: 'ベンチプレスの補助のグリップについて、正しいものは次のうちどれ', choices: [{ label: 'a', text: 'オルタネイティッドで補助をする' }, { label: 'b', text: 'スピネイティッドで補助をする' }, { label: 'c', text: 'プロネイティッドで補助をする' }], correct_choice: 'a', explanation: 'ベンチプレスはオルタネイティッドで補助を行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-3b-a-06', category_id: 'cat-3b', body: 'ダンベルフライの補助の仕方として、正しいのは次のうちどれ', choices: [{ label: 'a', text: '肘を支えて補助をする' }, { label: 'b', text: '補助は必要ない' }, { label: 'c', text: '手首を支えて補助をする' }], correct_choice: 'c', explanation: '肘を支えての補助はNSCAでは非推奨になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-3b-a-07', category_id: 'cat-3b', body: '補助が必要な種目は次のうちどれ', choices: [{ label: 'a', text: 'ジャーク' }, { label: 'b', text: 'ダンベルフライ' }, { label: 'c', text: 'デットリフト' }], correct_choice: 'b', explanation: 'パワーエクササイズの種目は補助者必要なく、デットリフトは顔面付近をバーが通過しないエクササイズの為、該当しない。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-3b-a-08', category_id: 'cat-3b', body: 'ダンベルベンチプレスの補助の仕方として、正しいのは次のうちどれ', choices: [{ label: 'a', text: '肘を支えて補助をする' }, { label: 'b', text: '手首を支えて補助をする' }, { label: 'c', text: '補助は必要ない' }], correct_choice: 'b', explanation: '肘を支えての補助はNSCAでは非推奨になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-3b-a-09', category_id: 'cat-3b', body: '補助が必要ない種目は次のうちどれ', choices: [{ label: 'a', text: 'パワースナッチ' }, { label: 'b', text: 'トライセプスエクステンション' }, { label: 'c', text: 'ライイングダンベルプルオーバー' }], correct_choice: 'a', explanation: 'パワーエクササイズの補助は必要ない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-3b-a-10', category_id: 'cat-3b', body: 'ライイングダンベルプルオーバー（ダンベル1つ）の補助の仕方として、正しいのは次のうちどれ', choices: [{ label: 'a', text: '挙上者の手首を支えて補助をする' }, { label: 'b', text: 'ダンベルそのものを支えて補助をする' }, { label: 'c', text: '肘を支えて補助をする' }], correct_choice: 'b', explanation: 'ダンベルが1つの場合、補助者はダンベルそのものを支える', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-3b-a-11', category_id: 'cat-3b', body: 'フォワードランジの補助の仕方として、正しいものは次のうちどれ', choices: [{ label: 'a', text: '後ろに1人で補助をする' }, { label: 'b', text: '両端に1人ずつと後ろに1人の計3人で補助をする' }, { label: 'c', text: '補助は必要ない' }], correct_choice: 'b', explanation: 'フォワードランジはスクワットと同様に下半身の種目であり、両端に1人ずつと後ろに1人の計3人での補助が基本となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-3b-a-12', category_id: 'cat-3b', body: 'ダンベルを2つ使用する種目で、補助者が肘を支えて補助するのは正しいか', choices: [{ label: 'a', text: '正しい' }, { label: 'b', text: 'NSCAでは非推奨である' }, { label: 'c', text: 'ダンベルが重い場合のみ許可されている' }], correct_choice: 'b', explanation: 'ダンベルを2つ使用する場合、補助者は挙上者の手首を支える。肘の補助はNSCAでは非推奨', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-3b-a-13', category_id: 'cat-3b', body: '上半身のバーベル種目で補助が必要な条件として正しいのは次のうちどれ', choices: [{ label: 'a', text: '重量が重い種目のみ補助が必要' }, { label: 'b', text: '顔面付近をバーが通過するエクササイズが補助の対象' }, { label: 'c', text: 'すべてのバーベル種目で補助が必要' }], correct_choice: 'b', explanation: '上半身のバーベル種目は、基本的に顔面付近をバーが通過するエクササイズが補助の対象となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
];
