import { Question } from '../../types';

export const CAT3J_QUESTIONS: Question[] = [
// III-J-a: プライオメトリック（12問）
  { id: 'q-3j-a-01', category_id: 'cat-3j', body: 'デブスジャンプにて負荷を漸進したい場合、正しいのは次のうちどれ', choices: [{ label: 'a', text: '重りを持って行う' }, { label: 'b', text: 'ボックスの高さを上げる' }, { label: 'c', text: '片足で行う' }], correct_choice: 'b', explanation: 'デブスジャンプの負荷を調整する場合はボックスの高さにて調整する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-3j-a-02', category_id: 'cat-3j', body: '次のプライオメトリックのうち、低強度ではないものは次のうちどれ', choices: [{ label: 'a', text: 'スタンディングロングジャンプ' }, { label: 'b', text: 'ダブルレッグ・バーティカルジャンプ' }, { label: 'c', text: 'ファストレッグ' }], correct_choice: 'c', explanation: 'ファストレッグは高強度となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-3j-a-03', category_id: 'cat-3j', body: 'プライオメトリックの筋活動の順番において、正しいもはどれ\n①コンセントリック ②エキセントリック ③アイソメトリック ④償却局面', choices: [{ label: 'a', text: '② →④ →③' }, { label: 'b', text: '② →④ →①' }, { label: 'c', text: '① →③ →②' }], correct_choice: 'b', explanation: 'プライオメトリックの筋活動は、エキセントリック- 償却局面 - コンセントリック', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-3j-a-04', category_id: 'cat-3j', body: '次のプライオメトリックのうち、高強度ではないものは次のうちどれ', choices: [{ label: 'a', text: 'フロントバリアホップ' }, { label: 'b', text: 'シングルレッグジャンプ' }, { label: 'c', text: 'ラテラルバウンド' }], correct_choice: 'a', explanation: 'フロントバリアホップは中強度となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-3j-a-05', category_id: 'cat-3j', body: 'プライオメトリックの目的は次のうちどれ', choices: [{ label: 'a', text: '最大筋力の向上' }, { label: 'b', text: '筋パワーの向上' }, { label: 'c', text: '持久力の向上' }], correct_choice: 'b', explanation: 'プライオメトリックの目的は筋パワーの向上（瞬発力）', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-3j-a-06', category_id: 'cat-3j', body: 'プライオメトリックでの償却局面において、重要なのは次のうちどれ', choices: [{ label: 'a', text: '長くする' }, { label: 'b', text: '短くする' }, { label: 'c', text: '一定にする' }], correct_choice: 'b', explanation: '償却局面が長いと伸長性局面で貯めたエネルギーがなくなってしまう為、短くすることが重要。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-3j-a-07', category_id: 'cat-3j', body: 'プライオメトリックを行える条件として正しいのはどれか\n体重の①＿%の重さでスクワットやベンチプレスが ②＿秒以内に③＿回持てる', choices: [{ label: 'a', text: '①65　②3　③5' }, { label: 'b', text: '①55　②5　③3' }, { label: 'c', text: '①60　②5　③5' }], correct_choice: 'c', explanation: '体重の60%の重さでスクワットやベンチプレスが5秒以内に5回持てる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-3j-a-08', category_id: 'cat-3j', body: '次のプライオメトリックのうち、中強度ではないものは次のうちどれ', choices: [{ label: 'a', text: 'アンクルホップ' }, { label: 'b', text: '交互バウンド' }, { label: 'c', text: '45°シットアップ' }], correct_choice: 'a', explanation: 'アンクルホップは低強度となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-3j-a-09', category_id: 'cat-3j', body: '初心者がプライオメトリックで最初に行うものは次のうちどれ', choices: [{ label: 'a', text: 'ダブルレッグ・バーティカルジャンプ' }, { label: 'b', text: 'デブスジャンプ' }, { label: 'c', text: 'ダブルレッグ・タックジャンプ' }], correct_choice: 'a', explanation: '初心者がはじめに行うのは低強度のものから行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-3j-a-10', category_id: 'cat-3j', body: 'デブスジャンプにて着地時に足が前後に開いてしまう場合、適切な指導は次のうちどれ', choices: [{ label: 'a', text: 'デブスジャンプを中止する' }, { label: 'b', text: '腕を振りすぎないようにアドバイスする' }, { label: 'c', text: 'ボックスの高さを下げ、着地時の練習を行う' }], correct_choice: 'c', explanation: 'ボックスの高さを下げて強度をさげ、着地時の練習に絞り行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-3j-a-11', category_id: 'cat-3j', body: 'プライオメトリックを行える条件として正しい数値を選べ\n体重の＿倍以上の重さでスクワットができる', choices: [{ label: 'a', text: '1.0' }, { label: 'b', text: '1.5' }, { label: 'c', text: '2.0' }], correct_choice: 'b', explanation: '体重の1.5倍以上の重さでスクワットができることがプライオメトリックを行える条件の一つ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-3j-a-12', category_id: 'cat-3j', body: 'プライオメトリックを行える条件として正しい数値を選べ\n体重と＿倍でベンチプレスが持てる', choices: [{ label: 'a', text: '0.5' }, { label: 'b', text: '1' }, { label: 'c', text: '1.5' }], correct_choice: 'b', explanation: '体重と同じ重さ（1倍）でベンチプレスが持てることがプライオメトリックを行える条件の一つ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
];
