import { Question } from '../../types';

export const CAT3K_QUESTIONS: Question[] = [
// III-K-a: スプリント・有酸素トレーニング（19問）
  { id: 'q-3k-a-01', category_id: 'cat-3k', body: '健康のための有酸素トレーニングの適切な頻度は次のうちどれ', choices: [{ label: 'a', text: '週2~3回' }, { label: 'b', text: '週2~5回' }, { label: 'c', text: '週3~5回' }], correct_choice: 'a', explanation: '有酸素トレーニングでの適切な頻度は週2~3回。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-3k-a-02', category_id: 'cat-3k', body: '健康のための有酸素トレーニングの適切な時間は次のうちどれ', choices: [{ label: 'a', text: '10~30分' }, { label: 'b', text: '20~40分' }, { label: 'c', text: '20~60分' }], correct_choice: 'c', explanation: '有酸素トレーニングでの適切な時間は20~60分', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-3k-a-03', category_id: 'cat-3k', body: '自由形（水泳）腕のストロークの推進力は次のうちどれ', choices: [{ label: 'a', text: '70~80%' }, { label: 'b', text: '80~90%' }, { label: 'c', text: '60~70%' }], correct_choice: 'b', explanation: '自由形の腕のストロークの推進力は80~90%になる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-3k-a-04', category_id: 'cat-3k', body: 'トレッドミルのハンドレール両手握りのクライアントへの漸進の方法は次のうちどれ', choices: [{ label: 'a', text: 'ハンドレールから両手を離す' }, { label: 'b', text: '片手でハンドレールを握る' }, { label: 'c', text: '両手の指２本ずつで支える' }], correct_choice: 'c', explanation: '両手で握っているクライアントに対しては両手の指2本ずつで支える事が適した漸進になる。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-3k-a-05', category_id: 'cat-3k', body: 'トレッドミルの説明として最も適切なものは次のうちどれ', choices: [{ label: 'a', text: '傾斜を１°つけると野外で走ったときとほぼ同じエネルギー消費量になる' }, { label: 'b', text: 'ハンドレールを握る事でエネルギー消費量が増える' }, { label: 'c', text: '野外で走るよりの安全性がない' }], correct_choice: 'a', explanation: 'トレッドミルに1°傾斜をつける事によって野外でのランニングとほぼ同じになる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-3k-a-06', category_id: 'cat-3k', body: 'スプリントにおけるプライオメトリックトレーニングの効果は次のうちどれ', choices: [{ label: 'a', text: 'スプリント頻度の増加' }, { label: 'b', text: 'どちらでもない' }, { label: 'c', text: 'ストライド長の増加' }], correct_choice: 'c', explanation: '', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-3k-a-07', category_id: 'cat-3k', body: 'ストライド頻度を伸ばすのに適切なものは次のうちどれ', choices: [{ label: 'a', text: 'アシステッドスプリント' }, { label: 'b', text: 'レジスティッドスプリント' }, { label: 'c', text: 'スクワット' }], correct_choice: 'a', explanation: 'ストライド頻度を伸ばすには、アシストが必要となり、自分が出せる100%以上のスピードで走る必要がある', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-3k-a-08', category_id: 'cat-3k', body: 'ウォーキング・スプリント着地から地面をけるまでの順番は次のうちどれ', choices: [{ label: 'a', text: '④→③→②→①' }, { label: 'b', text: '②→③→④→①' }, { label: 'c', text: '④→②→③→①' }], correct_choice: 'a', explanation: '着地から地面をけるまでは 踵のやや外側→小趾球→母趾球→親指', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-3k-a-09', category_id: 'cat-3k', body: 'ローイングエルゴメーターの正しい手順は次のうちどれ', choices: [{ label: 'a', text: '上体の後傾→股、膝関節の伸展→肘関節の屈曲' }, { label: 'b', text: '股、膝関節の伸展→上体の後傾→股、膝関節の伸展' }, { label: 'c', text: '上体の後傾→肘関節の屈曲→股、膝関節の伸展' }], correct_choice: 'a', explanation: 'ローイングエルゴメーターの動きの手順としては上体が後傾し、それに伴い股、膝関節の伸展と同時のタイミングで肘関節の屈曲', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-3k-a-10', category_id: 'cat-3k', body: 'ストライド長を伸ばすのに適切なものは次のうちどれ', choices: [{ label: 'a', text: 'アシステッドスプリント' }, { label: 'b', text: '下り坂走' }, { label: 'c', text: 'レジスティッドスプリント' }], correct_choice: 'c', explanation: 'ストライド長を伸ばすのには走る際に負荷がかかり、筋力と筋パワーを高める必要。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-3k-a-11', category_id: 'cat-3k', body: 'スプリントの最大速度時に適切な身体の角度は次のうちどれ', choices: [{ label: 'a', text: '10°' }, { label: 'b', text: '5°' }, { label: 'c', text: '12°' }], correct_choice: 'b', explanation: '最大速度に向けて徐々に身体が起きてきて身体は5°', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-3k-a-12', category_id: 'cat-3k', body: 'ステーショナリーバイクのサドル調整で誤っているものは次のうちどれ', choices: [{ label: 'a', text: 'かかとでペダルを踏み一番下に達した際に膝が伸び切る' }, { label: 'b', text: '漕ぎやすい高さを好みで調整する' }, { label: 'c', text: '拇指球でペダルを踏み一番下に達した際に膝がやや曲がる' }], correct_choice: 'b', explanation: 'サドルの調整は…拇指球でペダルを踏み一番下に達した際に、膝がやや曲がりかかとでペダルを踏み一番下に達した際に、膝が伸び切る高さ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-3k-a-13', category_id: 'cat-3k', body: 'スプリントの初期加速局面時に適切な身体の角度は次のうちどれ', choices: [{ label: 'a', text: '50°' }, { label: 'b', text: '45°' }, { label: 'c', text: '30°' }], correct_choice: 'b', explanation: '初期加速時は加速の為、大きく倒れており身体は45°', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-3k-a-14', category_id: 'cat-3k', body: 'ウォーキングにて誤っているものは次のうちどれ', choices: [{ label: 'a', text: '肘の角度は90度' }, { label: 'b', text: '腕を左右に振る' }, { label: 'c', text: '胸を張って歩く' }], correct_choice: 'b', explanation: 'ウォーキングは胸を張り、肘の角度は90度くらいにし胸まで上げて腰まで下げる腕は左右に振らない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-3k-a-15', category_id: 'cat-3k', body: '有酸素トレーニングの適切な強度の心拍数は次のうちどれ', choices: [{ label: 'a', text: '40~70% / 予備心拍数' }, { label: 'b', text: '50~75% / 予備心拍数' }, { label: 'c', text: '50~85% / 予備心拍数' }], correct_choice: 'c', explanation: '有酸素トレーニングでの適切な強度の心拍数は50~85% /予備心拍数。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-3k-a-16', category_id: 'cat-3k', body: 'ステアクライマーのやり方として最も適切なものは次のうちどれ', choices: [{ label: 'a', text: 'ペダルから踵ははみ出す' }, { label: 'b', text: '膝をつま先より前に出さない' }, { label: 'c', text: '姿勢は若干前傾姿勢' }], correct_choice: 'b', explanation: 'ステアクライマーはペダルから踵ははみ出さず、姿勢は直立で有ること。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },
  { id: 'q-3k-a-17', category_id: 'cat-3k', body: '競歩について正しいものは次のうちどれ', choices: [{ label: 'a', text: '膝は少し曲げた状態' }, { label: 'b', text: '腕を大きく降って跳ねる' }, { label: 'c', text: '常にどちらかの足が地面についている' }], correct_choice: 'c', explanation: '競歩のルールとして常にどちらかの足を地面についていなければならない。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 17 },
  { id: 'q-3k-a-18', category_id: 'cat-3k', body: 'スプリント最大速度局面の地面からの身体の角度は次のうちどれ', choices: [{ label: 'a', text: '65°' }, { label: 'b', text: '85°' }, { label: 'c', text: '75°' }], correct_choice: 'b', explanation: 'スプリント時の最大速度局面の身体の角度は5°', source: 'NEXT TRAINER LAB', is_free: true, display_order: 18 },
  { id: 'q-3k-a-19', category_id: 'cat-3k', body: 'スプリント初期局面の地面からの身体の角度は次のうちどれ', choices: [{ label: 'a', text: '30°' }, { label: 'b', text: '15°' }, { label: 'c', text: '45°' }], correct_choice: 'c', explanation: 'スプリント時の初期局面の地面から身体の角度は45°', source: 'NEXT TRAINER LAB', is_free: true, display_order: 19 },

// III-K-b: 無酸素性の適応・オーバートレーニング（8問）
  { id: 'q-3k-b-01', category_id: 'cat-3k', body: 'オーバートレーニングの指標で誤っているものは次のうちどれ', choices: [{ label: 'a', text: '体脂肪率の減少' }, { label: 'b', text: '最大化運動時の心拍数の低下' }, { label: 'c', text: '最大酸素摂取量の低下' }], correct_choice: 'b', explanation: 'オーバートレーニングの指標はとして最大化運動時の心拍数は上昇する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 20 },
  { id: 'q-3k-b-02', category_id: 'cat-3k', body: 'オーバートレーニングの指標で減少しないものは次のうちどれ', choices: [{ label: 'a', text: '筋グリコーゲン' }, { label: 'b', text: 'コルチゾール濃度' }, { label: 'c', text: '体脂肪率' }], correct_choice: 'b', explanation: 'オーバートレーニングの指標としてコルチゾール濃度は上昇する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 21 },
  { id: 'q-3k-b-03', category_id: 'cat-3k', body: 'レジスタンストレーニング短期的適応は次のうちどれ', choices: [{ label: 'a', text: 'ミトコンドリアの数が減少' }, { label: 'b', text: '神経の成長' }, { label: 'c', text: '運動単位動員数の減少' }], correct_choice: 'b', explanation: '無酸素性の適応表の表通り', source: 'NEXT TRAINER LAB', is_free: true, display_order: 22 },
  { id: 'q-3k-b-04', category_id: 'cat-3k', body: 'オーバートレーニングの指標で正しいものは次のうちどれ', choices: [{ label: 'a', text: '筋力が極端に増加する' }, { label: 'b', text: '疲れやすくなる' }, { label: 'c', text: '睡眠が深くなる' }], correct_choice: 'b', explanation: 'オーバートレーニングの指標として筋肉痛がとれないなど疲れやすくなる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 23 },
  { id: 'q-3k-b-05', category_id: 'cat-3k', body: 'レジスタンストレーニング長期的適応は次のうちどれ', choices: [{ label: 'a', text: '筋肥大' }, { label: 'b', text: 'ATP濃度の増加' }, { label: 'c', text: 'ミトコンドリアの活性化が増加' }], correct_choice: 'b', explanation: '無酸素性の適応表の表通り', source: 'NEXT TRAINER LAB', is_free: true, display_order: 24 },
  { id: 'q-3k-b-06', category_id: 'cat-3k', body: 'レジスタンストレーニング短期的適応ではないものは次のうちどれ', choices: [{ label: 'a', text: 'エキササイズテクニックの向上' }, { label: 'b', text: '発火頻度の減少' }, { label: 'c', text: '運動単位動員のタイミングが一致する' }], correct_choice: 'b', explanation: '短期的適応では運動単位の発火頻度が増加', source: 'NEXT TRAINER LAB', is_free: true, display_order: 25 },
  { id: 'q-3k-b-07', category_id: 'cat-3k', body: 'レジスタンストレーニング長期的適応ではないものは次のうちどれ', choices: [{ label: 'a', text: '毛細血管密度の増加' }, { label: 'b', text: 'エクササイズ中の乳酸減少' }, { label: 'c', text: '筋肥大' }], correct_choice: 'a', explanation: '長期的適応では毛細血管密度は減少する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 26 },
  { id: 'q-3k-b-08', category_id: 'cat-3k', body: 'レジスタンストレーニング始めてわずかの筋力向上の要因は次のうちどれ', choices: [{ label: 'a', text: '筋肥大' }, { label: 'b', text: 'ATP濃度の増加' }, { label: 'c', text: 'エササイズテクニックの向上' }], correct_choice: 'c', explanation: '始めてわずかの筋力向上の要因はエキササイズテクニックの向上である', source: 'NEXT TRAINER LAB', is_free: true, display_order: 27 },

// III-K-c: 有酸素性の適応（6問）
  { id: 'q-3k-c-01', category_id: 'cat-3k', body: '有酸素トレーニング３ヶ月の筋繊維変化は次のうちどれ', choices: [{ label: 'a', text: 'タイプⅡx→タイプⅡA' }, { label: 'b', text: 'タイプⅡA→タイプⅡx' }, { label: 'c', text: 'タイプⅠ→タイプⅡ' }], correct_choice: 'a', explanation: '３ヶ月行ったので長期的適応になる。筋繊維は持久力がついてくるためタイプⅡxからタイプⅡAになる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 28 },
  { id: 'q-3k-c-02', category_id: 'cat-3k', body: '有酸素トレーニング6週間の呼吸頻度変化は次のうちどれ', choices: [{ label: 'a', text: '減少' }, { label: 'b', text: '変わらない' }, { label: 'c', text: '増加' }], correct_choice: 'c', explanation: '6週間行ったので短期的適応になり、呼吸頻度は増加する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 29 },
  { id: 'q-3k-c-03', category_id: 'cat-3k', body: '有酸素トレーニング長期的適応で増加しないものは次のうちどれ', choices: [{ label: 'a', text: 'コルチゾール濃度' }, { label: 'b', text: 'グリコーゲンの貯蔵度' }, { label: 'c', text: '血液量' }], correct_choice: 'a', explanation: 'コルチゾール濃度の増加はオーバートレーニングの指標となる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 30 },
  { id: 'q-3k-c-04', category_id: 'cat-3k', body: '有酸素トレーニング短期的適応ではないものは次のうちどれ', choices: [{ label: 'a', text: '心臓肥大による1回拍出量の増加' }, { label: 'b', text: '心拍出量の増加' }, { label: 'c', text: '呼吸頻度の増加' }], correct_choice: 'a', explanation: '短期的適応でも１回拍出量は増加するが、心臓肥大によるものではない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 31 },
  { id: 'q-3k-c-05', category_id: 'cat-3k', body: '有酸素トレーニング短期的適応は次のうちどれ', choices: [{ label: 'a', text: '心拍数の増加' }, { label: 'b', text: 'ミトコンドリア数と活性化レベルの増加' }, { label: 'c', text: 'グリコーゲンの貯蔵量増加' }], correct_choice: 'a', explanation: 'グリコーゲンの貯蔵度増加とミトコンドリア数と活性化レベルの増加は長期的適応', source: 'NEXT TRAINER LAB', is_free: true, display_order: 32 },
  { id: 'q-3k-c-06', category_id: 'cat-3k', body: '有酸素トレーニング長期的適応は次のうちどれ', choices: [{ label: 'a', text: '少毛細血管密度の減' }, { label: 'b', text: '最大運動時における心拍数の減少' }, { label: 'c', text: 'ミトコンドリア数の減少' }], correct_choice: 'b', explanation: '有酸素トレーニングの長期的適応では、無酸素性トレーニングとは逆で毛細血管密度とミトコンドリア数は増加する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 33 },
];
