import { Question } from '../../types';

export const CAT3I_QUESTIONS: Question[] = [
// III-I-a: ストレッチ・生理的メカニズム（10問）
  { id: 'q-3i-a-01', category_id: 'cat-3i', body: 'PNFストレッチで最初に行う事は次のうちどれ', choices: [{ label: 'a', text: 'パッシブストレッチ' }, { label: 'b', text: 'コンセントリックアクション' }, { label: 'c', text: 'アクティブストレッチ' }], correct_choice: 'a', explanation: 'アクティブストレッチとは能動態、つまり自らストレッチを行っている', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-3i-a-02', category_id: 'cat-3i', body: '動的ストレッチではないものは次のうちどれ', choices: [{ label: 'a', text: 'ダイナミックストレッチ' }, { label: 'b', text: 'バリスティックストレッチ' }, { label: 'c', text: 'スタティックストレッチ' }], correct_choice: 'c', explanation: '反動を利用しリズミカルに筋を伸張する＝バリスティックストレッチ 拮抗する筋肉の収縮を促して対象の筋肉を伸ばす=ダイナミックストレッチ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-3i-a-03', category_id: 'cat-3i', body: 'ゴルジ腱器官の説明として正しいものは次のうちどれ', choices: [{ label: 'a', text: '腱の伸張を感知する役割' }, { label: 'b', text: '筋の伸張を感知する役割' }, { label: 'c', text: '伸長反射が起こる' }], correct_choice: 'a', explanation: 'ゴルジ腱器官は腱の伸張を感知する役割をしている', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-3i-a-04', category_id: 'cat-3i', body: '筋紡錘の説明として正しいものは次のうちどれ', choices: [{ label: 'a', text: 'トレーニングにより働きが弱くなる' }, { label: 'b', text: '筋の伸張を感知する役割' }, { label: 'c', text: '腱の伸張を感知する役割' }], correct_choice: 'b', explanation: '筋紡錘は筋の伸張を感知する役割をしている', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-3i-a-05', category_id: 'cat-3i', body: 'PNFストレッチの長期的な効果は次のうちどれ', choices: [{ label: 'a', text: '柔軟性の向上 + 筋力UP' }, { label: 'b', text: '柔軟性の向上 + 神経系の向上' }, { label: 'c', text: '柔軟性の向上' }], correct_choice: 'a', explanation: '長期的な効果として柔軟性だけでなく、筋力UPも見られる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-3i-a-06', category_id: 'cat-3i', body: '柔軟性の定義は次のうちどれ', choices: [{ label: 'a', text: '筋の伸張性' }, { label: 'b', text: '関節における可動域' }, { label: 'c', text: '筋の弾力性' }], correct_choice: 'b', explanation: '柔軟性の定義は関節における可動域を示す', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-3i-a-07', category_id: 'cat-3i', body: '静的ストレッチの一定保持時間は次のうちどれ', choices: [{ label: 'a', text: '30~45秒' }, { label: 'b', text: '15~30秒' }, { label: 'c', text: '5~10秒' }], correct_choice: 'b', explanation: '反動を利用しない静的ストレッチ＝スタティックストレッチ (15~30秒行う)', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-3i-a-08', category_id: 'cat-3i', body: 'ストレッチが必ずしも必要でないエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'エアロバイク' }, { label: 'b', text: 'バレーボール' }, { label: 'c', text: '100m走' }], correct_choice: 'a', explanation: 'エアロバイクやウォーキングなどは必ずしもストレッチが必要ではない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-3i-a-09', category_id: 'cat-3i', body: 'PNFストレッチの刺激でゴルジ腱器官が引き起こす反応は次のうちどれ', choices: [{ label: 'a', text: '主働筋自体の収縮に伴う弛緩' }, { label: 'b', text: '主働筋の収縮に伴う拮抗筋の弛緩' }, { label: 'c', text: '拮抗筋の弛緩に伴う主働筋の弛緩' }], correct_choice: 'a', explanation: '', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-3i-a-10', category_id: 'cat-3i', body: 'PNFストレッチにおいて利用する筋活動は次のうちどれ', choices: [{ label: 'a', text: 'アイソメトリック' }, { label: 'b', text: 'コンセントリック' }, { label: 'c', text: 'エキセントリック' }], correct_choice: 'a', explanation: 'アイソメトリック＝等尺性収縮を利用して行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
];
