import { Question } from '../../types';

export const CAT3F_QUESTIONS: Question[] = [
// III-F-a: エクササイズの種類（11問）
  { id: 'q-3f-a-01', category_id: 'cat-3f', body: 'ストラクチャルエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'ダンベルショルダープレス' }, { label: 'b', text: 'ベンチプレス' }, { label: 'c', text: 'ラテラルレイズ' }], correct_choice: 'a', explanation: 'ダンベルショルダープレスは背骨に対して負荷がかかるので、ストラクチャルエクササイズとなる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-3f-a-02', category_id: 'cat-3f', body: 'コアエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'スクワット' }, { label: 'b', text: 'バイセップスカール' }, { label: 'c', text: 'トライセプスエクステンション' }], correct_choice: 'a', explanation: 'スクワットは股関節と膝関節の2つ以上となるためコアエクササイズ。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-3f-a-03', category_id: 'cat-3f', body: '補助エクササイズは次のうちどれ', choices: [{ label: 'a', text: 'ベンチプレス' }, { label: 'b', text: 'バックエクステンション' }, { label: 'c', text: 'スクワット' }], correct_choice: 'b', explanation: 'バックエクステンションは膝関節のみが動くので補助エクササイズ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-3f-a-04', category_id: 'cat-3f', body: 'ストラクチャルエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'ベンチプレス' }, { label: 'b', text: 'バックスクワット' }, { label: 'c', text: 'ラットプルダウン' }], correct_choice: 'b', explanation: 'バックスクワットは背骨に対して負荷がかかるためストラクチャルエクササイズとなる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-3f-a-05', category_id: 'cat-3f', body: 'ストラクチャルエクササイズの定義は次のうちどれ', choices: [{ label: 'a', text: '瞬発的に速い動作で行われるエクササイズ' }, { label: 'b', text: '背骨に対してに負荷がかかるエクササイズ' }, { label: 'c', text: '2つ以上の主要な関節が関与するエクササイズ' }], correct_choice: 'b', explanation: 'ストラクチャルエクササイズは背骨に対して負荷がかかるエクササイズ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-3f-a-06', category_id: 'cat-3f', body: '瞬発的に速い動作で行われるエクササイズの定義は次のうちどれ', choices: [{ label: 'a', text: 'コアエクササイズ' }, { label: 'b', text: 'ストラクチャルエクササイズ' }, { label: 'c', text: 'パワーエクササイズ' }], correct_choice: 'c', explanation: 'パワーエクササイズは瞬発的に速い動作で行われるエクササイズ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-3f-a-07', category_id: 'cat-3f', body: 'コアエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'ラットプルダウン' }, { label: 'b', text: 'バイセップスカール' }, { label: 'c', text: 'レッグカール' }], correct_choice: 'a', explanation: 'ラットプルダウンは肩関節と肘関節が動くのでコアエクササイズとなる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-3f-a-08', category_id: 'cat-3f', body: 'スクワットとベンチプレスの両方に共通するエクササイズの種類は次のうちどれ', choices: [{ label: 'a', text: 'ストラクチャルエクササイズ' }, { label: 'b', text: '補助エクササイズ' }, { label: 'c', text: 'コアエクササイズ' }], correct_choice: 'c', explanation: 'スクワットのみだったらストラクチャルにも含まれるが、ベンチプレスがあるのでコアエクササイズとなる。', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-3f-a-09', category_id: 'cat-3f', body: '補助エクササイズの定義は次のうちどれ', choices: [{ label: 'a', text: '2つ以上の主要な関節が関与する' }, { label: 'b', text: '1つの主要な関節のみが関与する' }, { label: 'c', text: '背骨に対して負荷がかかる' }], correct_choice: 'b', explanation: '1つの主要な関節のみが関与するエクササイズ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-3f-a-10', category_id: 'cat-3f', body: 'ストラクチャルエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'フロントスクワット' }, { label: 'b', text: 'ベンチプレス' }, { label: 'c', text: 'ラットプルダウン' }], correct_choice: 'a', explanation: 'フロントスクワットは背骨に対して負荷がかかるため', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-3f-a-11', category_id: 'cat-3f', body: 'パワーエクササイズは次のうちどれ', choices: [{ label: 'a', text: 'バックスクワット' }, { label: 'b', text: 'パワークリーン' }, { label: 'c', text: 'デットリフト' }], correct_choice: 'b', explanation: 'パワークリーンは瞬間的に速い動作で行われる種目になるので、パワーエクササイズとなる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },

// III-F-b: エクササイズの配列（19問）
  { id: 'q-3f-b-01', category_id: 'cat-3f', body: 'ショルダープレスの次に行う種目として初心者に対して適切なのは次のうちどれ', choices: [{ label: 'a', text: 'ラテラルレイズ' }, { label: 'b', text: 'ベンチプレス' }, { label: 'c', text: 'バイセップスカール' }], correct_choice: 'c', explanation: '初心者の方は基本同じ部位を連続して行わない。三角筋が主働筋でないバイセップスカール', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-3f-b-02', category_id: 'cat-3f', body: 'パワークリーン→デットリフト→ベンチプレス→バイセップスカールの配列は次のうちどれ', choices: [{ label: 'a', text: '上半身と下半身を交互に行う配列' }, { label: 'b', text: '押すと引くを交互に行う配列' }, { label: 'c', text: '基本配列を用いた配列' }], correct_choice: 'c', explanation: 'パワークリーン(パワー)→デットリフト(ストラクチャル)→ベンチプレス（コア）→バイセップスカール（補助）', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
  { id: 'q-3f-b-03', category_id: 'cat-3f', body: 'コンパウンドセットの定義は次のうちどれ', choices: [{ label: 'a', text: '同じ部位の筋肉を連続して行う方法' }, { label: 'b', text: '主動筋（表）のあとに拮抗筋（裏）を交互に行う方法' }, { label: 'c', text: '上半身と下半身を交互に行う方法' }], correct_choice: 'a', explanation: 'コンパウンドセットは同じ部位の筋肉を連続して行う方法', source: 'NEXT TRAINER LAB', is_free: true, display_order: 14 },
  { id: 'q-3f-b-04', category_id: 'cat-3f', body: 'バイセップスカールのスーパーセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: 'ハンマーカール' }, { label: 'b', text: 'トライセプスエクステンション' }, { label: 'c', text: 'ラテラルレイズ' }], correct_choice: 'b', explanation: '上腕二頭筋（バイセップスカール）と上腕三頭筋（トライセプスエクステンション）の組み合わせ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 15 },
  { id: 'q-3f-b-05', category_id: 'cat-3f', body: 'スーパーセットの定義は次のうちどれ', choices: [{ label: 'a', text: '主動筋（表）のあとに拮抗筋（裏）を交互に行う方法' }, { label: 'b', text: '同じ部位の筋肉を連続して行う方法' }, { label: 'c', text: '上半身と下半身を交互に行う方法' }], correct_choice: 'a', explanation: 'スーパーセットは主働筋（表）のあとに拮抗筋（裏）を交互に行う方法', source: 'NEXT TRAINER LAB', is_free: true, display_order: 16 },
  { id: 'q-3f-b-06', category_id: 'cat-3f', body: 'ベンチプレスのコンパウンドセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: 'ベンチプレス – シーテッドロウ' }, { label: 'b', text: 'ベンチプレス – ダンベルフライ' }, { label: 'c', text: 'ベンチプレス – バイセップスカール' }], correct_choice: 'b', explanation: 'ベンチプレストダンベルフライはは両方大胸筋', source: 'NEXT TRAINER LAB', is_free: true, display_order: 17 },
  { id: 'q-3f-b-07', category_id: 'cat-3f', body: 'スクワットの次に行う種目として初心者に対して適切なのは次のうちどれ', choices: [{ label: 'a', text: 'レッグエクステンション' }, { label: 'b', text: 'フォワードランジ' }, { label: 'c', text: 'シーテッドカーフレイズ' }], correct_choice: 'c', explanation: '初心者の方は基本同じ部位を連続して行わない。スクワット(大腿部)→シーテッドカーフレイズ(下腿部)', source: 'NEXT TRAINER LAB', is_free: true, display_order: 18 },
  { id: 'q-3f-b-08', category_id: 'cat-3f', body: '①補助エクササイズ ②コアエクササイズ ③ストラクチャルエクササイズ ④パワーエクササイズ 基本配列は次のうちどれ', choices: [{ label: 'a', text: '④ →② →① →③' }, { label: 'b', text: '③ →④ →② →①' }, { label: 'c', text: '② →① →④ →③' }], correct_choice: 'a', explanation: '基本配列の通り', source: 'NEXT TRAINER LAB', is_free: true, display_order: 19 },
  { id: 'q-3f-b-09', category_id: 'cat-3f', body: 'ショルダープレスのコンパウンドセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: 'ベントオーバーロウ' }, { label: 'b', text: 'ベンチプレス' }, { label: 'c', text: 'ラテラルレイズ' }], correct_choice: 'c', explanation: 'ショルダープレスとラテラルレイズは両方三角筋の種目', source: 'NEXT TRAINER LAB', is_free: true, display_order: 20 },
  { id: 'q-3f-b-10', category_id: 'cat-3f', body: '①ベンチプレス ②シーテッドロウ ③アブドミナルクランチ ④バックエクステンション スーパーセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: '①と②' }, { label: 'b', text: '②と③' }, { label: 'c', text: '③と④' }], correct_choice: 'c', explanation: '腹直筋(アブドミナルクランチ)と脊柱起立筋(バックエクステンション)の組み合わせ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 21 },
  { id: 'q-3f-b-11', category_id: 'cat-3f', body: 'レッグエクステンションのスーパーセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: 'フォワードランジ' }, { label: 'b', text: 'レッグカール' }, { label: 'c', text: 'スクワット' }], correct_choice: 'b', explanation: 'ハムストリング（レッグエクステンション）と大腿四頭筋（レッグカール）の組み合わせ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 22 },
  { id: 'q-3f-b-12', category_id: 'cat-3f', body: '①コアエクササイズ ②補助エクササイズ ③ストラクチャルエクササイズ ④パワーエクササイズ 基本配列は次のうちどれ', choices: [{ label: 'a', text: '③ →④ →① →②' }, { label: 'b', text: '④ →③ →① →②' }, { label: 'c', text: '④ →① →③ →②' }], correct_choice: 'b', explanation: '', source: 'NEXT TRAINER LAB', is_free: true, display_order: 23 },
  { id: 'q-3f-b-13', category_id: 'cat-3f', body: 'ショルダープレス→ラットプルダウン→インクラインベンチプレス→アップライトロウの配列は次のうちどれ', choices: [{ label: 'a', text: '上半身と下半身を交互に行う' }, { label: 'b', text: '押すと引くを交互に行う' }, { label: 'c', text: '同じ部位を連続して行う' }], correct_choice: 'b', explanation: 'ショルダープレス(押す)→ラットプルダウン（引く）→インクラインベンチプレス（押す）→アップライトロウ（引く）', source: 'NEXT TRAINER LAB', is_free: true, display_order: 24 },
  { id: 'q-3f-b-14', category_id: 'cat-3f', body: '①ベンチプレス ②ラットプルダウン ③ペックデック ④シーテッドロウ スーパーセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: '①と②' }, { label: 'b', text: '②と③' }, { label: 'c', text: '③と④' }], correct_choice: 'c', explanation: '大胸筋(ペックデック)と広背筋(シーテッドロウ)の組み合わせ', source: 'NEXT TRAINER LAB', is_free: true, display_order: 25 },
  { id: 'q-3f-b-15', category_id: 'cat-3f', body: '①ラテラルレイズ ②スクワット ③フォワードランジ ④ベンチプレス コンパウンドセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: '①と④' }, { label: 'b', text: '①と②' }, { label: 'c', text: '②と③' }], correct_choice: 'c', explanation: 'スクワットとフォワードランジの両方大腿部の種目', source: 'NEXT TRAINER LAB', is_free: true, display_order: 26 },
  { id: 'q-3f-b-16', category_id: 'cat-3f', body: 'バイセップスカールのコンパウンドセットの組み合わせは次のうちどれ', choices: [{ label: 'a', text: 'ハンマーカール' }, { label: 'b', text: 'トライセプスエクステンション' }, { label: 'c', text: 'ラテラルレイズ' }], correct_choice: 'a', explanation: 'バイセップスカールとハンマーカールは両方上腕二頭筋の種目', source: 'NEXT TRAINER LAB', is_free: true, display_order: 27 },
  { id: 'q-3f-b-17', category_id: 'cat-3f', body: 'フォワードランジ→ペックデック→レッグカール→バイセップスカールの配列は次のうちどれ', choices: [{ label: 'a', text: '押すと引くを交互に行う' }, { label: 'b', text: '下半身と上半身を交互に行う' }, { label: 'c', text: '同じ部位を連続して行う' }], correct_choice: 'b', explanation: 'フォワードランジ(下半身)→ペックデック(上半身)→レッグカール(下半身)→バイセップスカール（上半身）', source: 'NEXT TRAINER LAB', is_free: true, display_order: 28 },
  { id: 'q-3f-b-18', category_id: 'cat-3f', body: '①ストラクチャルエクササイズ ②補助エクササイズ ③コアエクササイズ ④パワーエクササイズ 基本配列は次のうちどれ', choices: [{ label: 'a', text: '① →④ →③ →②' }, { label: 'b', text: '③ →① →④ →②' }, { label: 'c', text: '④ →② →① →③' }], correct_choice: 'c', explanation: '基本配列の通り', source: 'NEXT TRAINER LAB', is_free: true, display_order: 29 },
  { id: 'q-3f-b-19', category_id: 'cat-3f', body: '①パワーエクササイズ ②補助エクササイズ ③コアエクササイズ ④ストラクチャルエクササイズ 基本配列は次のうちどれ', choices: [{ label: 'a', text: '④ →① →③ →②' }, { label: 'b', text: '① →③ →④ →②' }, { label: 'c', text: '③ →① →④ →②' }], correct_choice: 'c', explanation: '', source: 'NEXT TRAINER LAB', is_free: true, display_order: 30 },
];
