import { Question } from '../../types';

export const CAT4B_QUESTIONS: Question[] = [
  { id: 'q-4b-a-01', category_id: 'cat-4b', body: 'AEDの設置についてADA（障害を持つアメリカ人法）のガイドラインに準拠しているのは次のうちどれか', choices: [{ label: 'a', text: '施設の入り口に設置' }, { label: 'b', text: '管理者の机に設置' }, { label: 'c', text: '車椅子の人が届く高さに設置' }], correct_choice: 'c', explanation: 'ADAガイドラインでは車椅子の人が届く高さに設置することが求められる', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-4b-a-02', category_id: 'cat-4b', body: '意識のあるクライアントが胸の痛みを訴えている場合、パーソナルトレーナーが取るべき行動として正しいのはどれか', choices: [{ label: 'a', text: 'AEDを使用する' }, { label: 'b', text: 'EMSを実施する' }, { label: 'c', text: '安静にしてもらう' }], correct_choice: 'b', explanation: '意識のあるクライアントが胸の痛みを訴えている場合はEMS（救急医療サービス）を実施する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-4b-a-03', category_id: 'cat-4b', body: '小児に対して成人用のAEDを使用する場合、正しい対応は次のうちどれか', choices: [{ label: 'a', text: '成人用AEDは使用しない' }, { label: 'b', text: 'パッドの位置を変えてAEDを使用する' }, { label: 'c', text: '成人用AEDをそのまま使用する' }], correct_choice: 'b', explanation: '小児に対して成人用AEDを使用する場合はパッドの位置を変えて使用する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-4b-a-04', category_id: 'cat-4b', body: 'パーソナルトレーニング中に事故が起きた場合、法的な責任を問われる可能性のある組み合わせとして正しいのはどれか', choices: [{ label: 'a', text: 'パーソナルトレーナー・施設のオーナー・クライアント' }, { label: 'b', text: 'パーソナルトレーナー・施設のオーナー' }, { label: 'c', text: 'パーソナルトレーナーのみ' }], correct_choice: 'a', explanation: 'パーソナルトレーナー・施設のオーナー・クライアントの全員が法的責任を問われる可能性がある', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-4b-a-05', category_id: 'cat-4b', body: '緊急時対応計画に含まれないものは次のうちどれか', choices: [{ label: 'a', text: 'スタッフの役割' }, { label: 'b', text: '重要な秘密の保持に関する書類' }, { label: 'c', text: '緊急連絡先' }], correct_choice: 'b', explanation: '重要な秘密の保持に関する書類は緊急時対応計画には含まれない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-4b-a-06', category_id: 'cat-4b', body: 'パーソナルトレーナーの役割と責任について正しいのは次のうちどれか', choices: [{ label: 'a', text: '治療・教育・動機付け' }, { label: 'b', text: '評価・教育・動機付け' }, { label: 'c', text: '治療・評価・動機付け' }], correct_choice: 'b', explanation: 'パーソナルトレーナーの役割は評価・教育・動機付けである。治療は含まれない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-4b-a-07', category_id: 'cat-4b', body: '労作性熱中症が疑われるクライアントに対して、最初に取るべき行動は次のうちどれか', choices: [{ label: 'a', text: '水分を補給させる' }, { label: 'b', text: '冷却活動を行う' }, { label: 'c', text: 'EMSに連絡する' }], correct_choice: 'b', explanation: '労作性熱中症が疑われる場合、最初に冷却活動を行う', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-4b-a-08', category_id: 'cat-4b', body: 'クライアントの自宅でトレーニングを行う際、器具の故障によりクライアントが怪我をした場合、責任を問われるのは次のうちどれか', choices: [{ label: 'a', text: 'クライアント' }, { label: 'b', text: '器具のメーカー' }, { label: 'c', text: 'トレーナー' }], correct_choice: 'c', explanation: 'クライアントの自宅でトレーニングを行う場合、器具の安全性を確認する責任はトレーナーにある', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-4b-a-09', category_id: 'cat-4b', body: 'クライアントがトレーナーに対して訴訟を起こすために必要な条件として正しいのは次のうちどれか', choices: [{ label: 'a', text: 'トレーナーに義務違反があった' }, { label: 'b', text: 'トレーナーが資格を持っていなかった' }, { label: 'c', text: 'トレーナーが保険に加入していなかった' }], correct_choice: 'a', explanation: '訴訟を起こすためにはトレーナーに義務違反があったことが必要', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-4b-a-10', category_id: 'cat-4b', body: 'パーソナルトレーナーの業務範囲を超える行為は次のうちどれか', choices: [{ label: 'a', text: '有酸素運動で持病がよくなる' }, { label: 'b', text: '有酸素運動を行う' }, { label: 'c', text: '有酸素運動のプログラムを組む' }], correct_choice: 'a', explanation: '有酸素運動で持病がよくなるという発言は医療行為に該当し、トレーナーの業務範囲を超える', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-4b-a-11', category_id: 'cat-4b', body: 'クライアントが軽度の捻挫をした場合、パーソナルトレーナーが最初に取るべき行動は次のうちどれか', choices: [{ label: 'a', text: 'EMSに連絡する' }, { label: 'b', text: 'ファーストエイドを実施する' }, { label: 'c', text: 'AEDを準備する' }], correct_choice: 'b', explanation: '生命に危険がない状況ではファーストエイドを実施する。EMSやAEDは生命に危険がある状況で使用する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
  { id: 'q-4b-a-12', category_id: 'cat-4b', body: 'クライアントが意識を失い呼吸も確認できない場合、パーソナルトレーナーが行うべき対応の組み合わせとして正しいのは次のうちどれか', choices: [{ label: 'a', text: 'EMSの実施のみ' }, { label: 'b', text: 'EMSの実施 + AED + CPR' }, { label: 'c', text: 'ファーストエイド + AED' }], correct_choice: 'b', explanation: '意識・呼吸がない場合は生命に危険がある状況であり、EMSの実施に加えてAEDとCPRも実施する', source: 'NEXT TRAINER LAB', is_free: true, display_order: 12 },
  { id: 'q-4b-a-13', category_id: 'cat-4b', body: 'パーソナルトレーナーが治療行為を行ってはならない理由として正しいのは次のうちどれか', choices: [{ label: 'a', text: '保険に加入していないため' }, { label: 'b', text: '診断権を保持していないため' }, { label: 'c', text: '施設の規則で禁止されているため' }], correct_choice: 'b', explanation: 'パーソナルトレーナーは診断権を保持していないため、治療行為を行ってはいけない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 13 },
];
