import { Question } from '../../types';

export const CAT4A_QUESTIONS: Question[] = [
  { id: 'q-4a-a-01', category_id: 'cat-4a', body: '3人分として最適なストレッチエリアの広さは次のうちどれ', choices: [{ label: 'a', text: '13.8㎡' }, { label: 'b', text: '12.6㎡' }, { label: 'c', text: '9.9㎡' }], correct_choice: 'a', explanation: '一人当たり4.6㎡必要なため', source: 'NEXT TRAINER LAB', is_free: true, display_order: 1 },
  { id: 'q-4a-a-02', category_id: 'cat-4a', body: 'ホームジムの機器配置にてバーとバーを離す適切な距離は次のうちどれ', choices: [{ label: 'a', text: '51cm' }, { label: 'b', text: '46cm' }, { label: 'c', text: '91cm' }], correct_choice: 'b', explanation: 'ホームジムなので91cmの約半分46cmの距離を取ること', source: 'NEXT TRAINER LAB', is_free: true, display_order: 2 },
  { id: 'q-4a-a-03', category_id: 'cat-4a', body: 'ジムの機器配置にてマシーンとマシーンを離す適切な距離は', choices: [{ label: 'a', text: '61cm' }, { label: 'b', text: '91cm' }, { label: 'c', text: '51cm' }, { label: 'd', text: '15cm' }], correct_choice: 'a', explanation: 'マシーンとマシーンの間隔は61cm', source: 'NEXT TRAINER LAB', is_free: true, display_order: 3 },
  { id: 'q-4a-a-04', category_id: 'cat-4a', body: 'トレーナーが最も気をつけて確認するものは次のうちどれ', choices: [{ label: 'a', text: '出入り口の周り' }, { label: 'b', text: 'マシーンのボルト点検' }, { label: 'c', text: 'マシーンの清掃' }], correct_choice: 'b', explanation: 'マシーンのボルト点検は毎日行わなければならない', source: 'NEXT TRAINER LAB', is_free: true, display_order: 4 },
  { id: 'q-4a-a-05', category_id: 'cat-4a', body: 'ジムの機器配置にて床から鏡までの適切な距離は', choices: [{ label: 'a', text: '61cm' }, { label: 'b', text: '91cm' }, { label: 'c', text: '51cm' }, { label: 'd', text: '15cm' }], correct_choice: 'c', explanation: '床から鏡までの距離は51cm', source: 'NEXT TRAINER LAB', is_free: true, display_order: 5 },
  { id: 'q-4a-a-06', category_id: 'cat-4a', body: 'ジムの機器配置にて壁とラックまでの適切な距離は', choices: [{ label: 'a', text: '15cm' }, { label: 'b', text: '61cm' }, { label: 'c', text: '51cm' }, { label: 'd', text: '91cm' }], correct_choice: 'd', explanation: '壁とラックの間隔は91cm', source: 'NEXT TRAINER LAB', is_free: true, display_order: 6 },
  { id: 'q-4a-a-07', category_id: 'cat-4a', body: 'ジムの天井の最低の高さはどれ', choices: [{ label: 'a', text: '3.5m' }, { label: 'b', text: '3.7m' }, { label: 'c', text: '3.0m' }], correct_choice: 'b', explanation: 'ジムの天井の最低の高さは3.7m', source: 'NEXT TRAINER LAB', is_free: true, display_order: 7 },
  { id: 'q-4a-a-08', category_id: 'cat-4a', body: 'ジムの機器配置にてバーと鏡までの適切な距離は', choices: [{ label: 'a', text: '15cm' }, { label: 'b', text: '51cm' }, { label: 'c', text: '91cm' }, { label: 'd', text: '61cm' }], correct_choice: 'a', explanation: 'バーと鏡の距離は15cm', source: 'NEXT TRAINER LAB', is_free: true, display_order: 8 },
  { id: 'q-4a-a-09', category_id: 'cat-4a', body: '床から15cm上がった高さにリフティングエリアがあるとき、鏡の高さはどれ', choices: [{ label: 'a', text: '51cm' }, { label: 'b', text: '66cm' }, { label: 'c', text: '78cm' }], correct_choice: 'b', explanation: '15cm分の高さがあるため51cmに15cmを足した高さが必要', source: 'NEXT TRAINER LAB', is_free: true, display_order: 9 },
  { id: 'q-4a-a-10', category_id: 'cat-4a', body: '最適な環境の気温と湿度の組み合わせは次のうちどれ', choices: [{ label: 'a', text: '気温：21~25℃ 湿度：55%' }, { label: 'b', text: '気温：22~26℃ 湿度：55%' }, { label: 'c', text: '気温：22~25℃ 湿度：50%' }], correct_choice: 'c', explanation: '最適な環境の気温は22~25℃ 湿度50%以下', source: 'NEXT TRAINER LAB', is_free: true, display_order: 10 },
  { id: 'q-4a-a-11', category_id: 'cat-4a', body: 'ジムの機器配置にてバーとバーを離す適切な距離は', choices: [{ label: 'a', text: '61cm' }, { label: 'b', text: '91cm' }, { label: 'c', text: '51cm' }, { label: 'd', text: '15cm' }], correct_choice: 'b', explanation: 'バーとバーの間隔は91cm', source: 'NEXT TRAINER LAB', is_free: true, display_order: 11 },
];
